export const APP_VERSION = "13.3.0";
export const APP_RELEASE_DATE = "2026-04-30";

export const APP_RELEASE_HIGHLIGHTS = [
    {
        title: "AccCalc 13.3.0 delivers a super-completion pass",
        body: "New AFAR, audit, tax, and AIS workspaces fill remaining high-value curriculum gaps while Study Hub adds more original reviewer and quiz coverage.",
    },
    {
        title: "Pages explain themselves faster",
        body: "Calculator and reviewer pages now surface a compact use-this-when, output, and next-step strip so users can understand the page before opening deeper help.",
    },
    {
        title: "Learn, practice, solve, and review are tighter",
        body: "New topics connect lessons, quizzes, Smart Solver, OCR routing, related page menus, and a v13.3 workpaper template for long-term study continuity.",
    },
    {
        title: "Completion coverage is more survivable",
        body: "The 13.3 study expansion emphasizes route choice, assumptions, and mistake repair across AFAR, audit, tax, AIS, FAR disclosure, bookkeeping, RFBT, and integrated CPA cases.",
    },
    {
        title: "AccCalc 13.2.0 adds guided onboarding",
        body: "First-time users now get an action-aware tutorial, while returning users get a lighter reintroduction prompt that can be skipped or replayed later.",
    },
    {
        title: "Tutorial steps respond to real actions",
        body: "The walkthrough can detect navigation, search, route changes, settings access, and calculator input interaction instead of behaving like a fixed slideshow.",
    },
    {
        title: "Settings becomes the help replay hub",
        body: "Settings now includes full tutorial replay, quick tour replay, and tutorial-state reset controls.",
    },
    {
        title: "Educational-use boundaries are clearer",
        body: "Tax, audit, legal/RFBT, AIS, and governance pages now surface integrated reminders that the tools are educational support and not current professional advice.",
    },
    {
        title: "AccCalc 13.1.0 completes a final high-value academic pass",
        body: "New audit, tax, AIS, governance, and RFBT routes strengthen weak core curriculum families with original lessons, quizzes, Smart Solver routing, OCR discovery, and workpaper support.",
    },
    {
        title: "Audit and tax review become more complete",
        body: "Materiality, misstatement pressure, income-tax payable, credits, payments, and overpayment review now connect computation with classroom response signals.",
    },
    {
        title: "AIS, governance, and RFBT get stronger reviewer workspaces",
        body: "Revenue-cycle controls, fraud-risk response, and negotiable-instrument issue spotting fill practical non-formula gaps in the academic system.",
    },
    {
        title: "Study Hub adds a final integrated practice layer",
        body: "New original lessons and quizzes teach route discipline across audit, tax, AIS, governance, RFBT, and intermediate-accounting review.",
    },
    {
        title: "Workpapers support mixed CPA-review documentation",
        body: "The v13.1 academic review support template gives students a place to record issue, route, result, limitation, practice follow-up, and status.",
    },
    {
        title: "Discovery remains connected across learn, practice, solve, and review",
        body: "App catalog/search, Smart Solver, Scan & Check, Study Hub, calculator page menus, and tests now know the new academic routes.",
    },
] as const;

export const APP_RELEASE_NOTES = [
    "13.3.0: Added Installment Sales Gross Profit Review for gross profit rate, realized gross profit, deferred gross profit, and repossession recovery signals.",
    "13.3.0: Added Going Concern Review Workspace for adverse conditions, management plans, evidence support, residual doubt, and completion-stage audit response.",
    "13.3.0: Added Tax Remedy Timeline Review for educational deadline pressure, evidence completeness, materiality, and procedural-complexity triage.",
    "13.3.0: Added Incident Response Triage for AIS confidentiality, integrity, availability, containment, evidence readiness, and IT-audit escalation support.",
    "13.3.0: Added original Study Hub lessons and quizzes for installment sales, going concern, tax remedies, incident response, FAR disclosure, closing cycle, corporation-law lifecycle, and integrated CPA case routing.",
    "13.3.0: Added a v13.3 Super-Completion Review Map workpaper template for recording lesson, quiz, workspace, result, limitation, next action, and status.",
    "13.3.0: Added first-screen page clarity strips across calculator/reviewer pages so users can see when to use the page, what it returns, and where to continue.",
    "13.3.0: Wired new workspaces into app catalog/search, Smart Solver, OCR routing, Study Hub links, related page menus, workpapers, and regression tests.",
    "13.2.0: Added a first-time-user tutorial that teaches Home, navigation, search, Smart Solver, calculator inputs, Study Hub, Workpapers, and Settings replay.",
    "13.2.0: Added a returning-user quick reintroduction prompt for the first open after this release, with skip and do-not-show-again controls.",
    "13.2.0: Added an action-aware onboarding engine with route, shell-action, search, settings, and input-interaction completion checks plus timeout fallback.",
    "13.2.0: Added Settings controls to replay the full tutorial, replay the quick tour, and reset local tutorial state.",
    "13.2.0: Added contextual educational-use notices for tax, audit, legal/RFBT, governance, and AIS reviewer surfaces.",
    "13.2.0: Moved test compilation output into an ignored cache path and removed tracked .test-dist generated files from the repository index.",
    "13.1.0: Added Audit Materiality and Misstatement Planner for planning materiality, performance materiality, clearly trivial thresholds, and misstatement cushion review.",
    "13.1.0: Added Income Tax Payable and Credits Review for taxable income, gross tax due, withholding credits, quarterly payments, refundable credits, penalties, payable, and overpayment signals.",
    "13.1.0: Added Revenue Cycle Control Review for AIS order-to-cash controls, assertion mapping, walkthrough evidence, weak control gaps, and audit follow-up.",
    "13.1.0: Added Fraud Risk Response Planner for fraud triangle, management override, evidence-quality concerns, audit response, and governance escalation.",
    "13.1.0: Added Negotiable Instruments Issue Spotter for holder status, defenses, party liability, presentment, dishonor, and notice review.",
    "13.1.0: Added original Study Hub lessons and quizzes for audit materiality, tax payable, AIS revenue controls, RFBT negotiable instruments, fraud-risk response, and intermediate-accounting route discipline.",
    "13.1.0: Wired the final academic expansion into app catalog/search, Smart Solver, OCR routing, related page menus, Study Hub recommendations, and a v13.1 workpaper template.",
    "13.1.0: Updated README, release notes, system overview, maintenance guidance, generated HTML/PDF documentation, and regression coverage for the final academic-completion pass.",
    "13.0.0: Added Conceptual Framework Recognition Helper for element classification, recognition support, measurement-basis selection, and disclosure cautions.",
    "13.0.0: Added Revenue Allocation Workspace for bundled transaction-price allocation, performance-obligation satisfaction, and contract asset or liability review.",
    "13.0.0: Added Taxable Income Bridge for accounting-income reconciliation, permanent and temporary differences, loss deductions, current tax, and deferred-tax signals.",
    "13.0.0: Added Audit Evidence Program Builder for assertion risk, evidence reliability, relevance, coverage, contradictory evidence, and procedure-intensity planning.",
    "13.0.0: Added Target Costing Workspace for market price, required profit, allowable cost, committed savings, and remaining cost-gap analysis.",
    "13.0.0: Added original Study Hub modules and quizzes for conceptual framework, revenue allocation, taxable income, target costing, audit evidence, and CPA practical financial accounting integration.",
    "13.0.0: Wired the new academic routes into app catalog/search, calculator related panels, Smart Solver routing, OCR routing, and an integrated v13 workpaper support template.",
    "13.0.0: Updated README, release notes, system overview, and maintenance guidance for the book-inspired academic expansion release.",
    "12.6.0: Expanded the overlay fix from mobile menu/settings into the shared support-surface system for page menus, media previews, scan previews, support QR views, and desktop settings.",
    "12.6.0: Widened tablet/laptop/desktop page menus into proper full-height side sheets so contextual page help no longer feels like a tiny card floating in unused space.",
    "12.6.0: Upgraded MediaViewerModal to use ViewportPortal, shared body scroll locking, safe-area-aware full-screen mobile layout, and large full-height desktop sizing.",
    "12.6.0: Improved support QR and scan image previews automatically through the shared media viewer overlay.",
    "12.6.0: Increased the desktop settings side-panel width with a responsive clamp so settings groups have more usable room on laptop and desktop screens.",
    "12.6.0: Updated README, release notes, system overview, and maintenance guidance for the broader support-surface viewport-fit contract.",
    "12.5.0: Reworked the mobile menu into a true full-screen viewport panel with safe-area padding, internal navigation scrolling, and no narrow drawer width cap.",
    "12.5.0: Reworked mobile settings into a full-screen panel for all non-desktop shell widths, removing side-sheet offsets, max-width constraints, and chrome-subtracted height math.",
    "12.5.0: Updated contextual page menus and mobile search overlay sizing so small-screen overlays use viewport-owned full-screen behavior instead of clipped page-remaining space.",
    "12.5.0: Tightened transient panel state so opening menu, search, or settings clears the other mobile surfaces instead of allowing awkward stacked overlay states.",
    "12.5.0: Adjusted the shared scroll lock to keep the background fixed while allowing vertical panning inside long overlay panels.",
    "12.5.0: Updated README, release notes, system overview, and maintenance guidance for the focused mobile overlay and shell reliability release.",
    "12.4.0: Added Audit Misstatement Evaluation Workspace, Segregation of Duties Conflict Matrix, and Governance Escalation Planner to strengthen weaker Audit, AIS, and Governance coverage with practical classroom decision tools.",
    "12.4.0: Added new FAR and managerial study topics for receivables estimation, cash discount discipline, cost behavior, and margin of safety, each with topic-specific quiz support and linked calculators.",
    "12.4.0: Tightened the lesson, quiz, and calculator loop so Study Hub topic cards, Practice Hub cards, weak-topic review panels, and quiz results now route students into the closest linked lesson or tool.",
    "12.4.0: Expanded Smart Solver and route discovery coverage for the new audit, AIS, and governance tools and sharpened segregation-of-duties prompts so they beat the broader access-control review when the prompt is really about incompatible duties.",
    "12.4.0: Expanded the theme system with palette-led families for Butter, Moss, Palm, Guava, Sunset, Sangria, Seabreeze, Lagoon, and Odyssey while preserving Classic as the default baseline.",
    "12.4.0: Reorganized Settings so Appearance now opens with a compact summary card, a smaller mode selector, a quick family strip, and a discoverable theme gallery instead of a large always-visible theme wall.",
    "12.4.0: Kept the earlier working theme families available so familiar Ocean, Slate, Rose, Blossom, Lavender, and Emerald selections continue to work alongside the newer palette families.",
    "12.4.0: Applied theme, family, contrast, motion, and meta theme-color state before React mounts to reduce visual flicker and make reload behavior more consistent.",
    "12.4.0: Strengthened the shared theme-token structure with cleaner family-driven chrome, accent, chip, chart, and workspace atmosphere variables.",
    "12.4.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the combined personalization and academic-expansion release.",
    "12.3.0: Rebuilt Smart Solver around topic-first routing so route families are classified before extraction and generic vocabulary no longer dominates calculator choice.",
    "12.3.0: Added route-family gating, contradiction pressure, and cleaner secondary-route separation so multi-concept prompts stop contaminating the primary prepared inputs.",
    "12.3.0: Moved Smart Solver UI summaries onto a selected-route source of truth so Best Match, confidence, interpreter feedback, prepared inputs, and open/apply actions stay aligned.",
    "12.3.0: Hardened extraction hygiene with stronger year/date, percent, and route-family field guards and improved intercompany transfer-price detection.",
    "12.3.0: Updated OCR parsing to use topic-first Smart Solver analysis, preserve comma-separated classroom amounts during normalization, and keep route-aware structured values cleaner before review.",
    "12.3.0: Added a reusable Smart Solver evaluation pack covering FAR, AFAR, Cost & Managerial, Audit, Tax, study-first, and OCR scenarios.",
    "12.3.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the Smart Solver and OCR precision release.",
    "12.2.0: Finished the shell viewport-fit pass by reserving top and bottom chrome space for page menus, mobile navigation, settings, search, and reminder overlays instead of letting temporary surfaces collide with app chrome.",
    "12.2.0: Removed redundant Learning Hub chrome so module shelves, recent lesson activity, and category browsing reach useful content faster with less label and chip noise.",
    "12.2.0: Rebuilt settings row layout rules with resilient grid and wrapping behavior so longer labels, selects, badges, and action buttons reflow cleanly on wider screens.",
    "12.2.0: Deferred disclosure body rendering, reduced repeated homepage status subscriptions, and trimmed low-value metadata so the app feels smoother during repeated daily use.",
    "12.2.0: Simplified shell context copy and page-menu framing so the focus-first system explains itself less and gets out of the user's way more often.",
    "12.2.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the shell-tightening and density-control release.",
    "12.1.0: Fixed the mobile menu root cause by portaling shell overlays to the viewport, removing shell clipping, and unifying live viewport-height handling for phones and small browsers.",
    "12.1.0: Added shared body-scroll locking so mobile navigation, settings, search, and page menus no longer compete with background scrolling or partial-screen overlays.",
    "12.1.0: Simplified the shell context rail and hid competing mobile chrome while transient panels are open, making navigation states clearer across phone, tablet, and desktop layouts.",
    "12.1.0: Reorganized the homepage around best-next surfaces, return flows, pinned tools, and delayed discovery instead of equal-weight content blocks.",
    "12.1.0: Moved lesson context into progressive disclosure and added a settings category map so reading and configuration flows stay more single-purpose.",
    "12.1.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the stabilized focus-first release.",
    "12.0.0: Added a shared page menu system so secondary guidance, related study, and nearby routes stop crowding calculator and workspace headers.",
    "12.0.0: Reworked CalculatorPageLayout to keep inputs and results primary while moving supporting detail into progressive-disclosure surfaces.",
    "12.0.0: Rebuilt the homepage around next-step decisions, primary entry points, and delayed discovery instead of a broad feature wall.",
    "12.0.0: Reduced study-page side clutter by converting module flow and lesson signals into lighter on-demand references.",
    "12.0.0: Added Workpaper Studio focus mode so workbook health, context, and side utilities can move out of the editing path when needed.",
    "12.0.0: Updated release docs and maintenance guidance to formalize the focus-first page philosophy for future additions.",
    "11.0.0: Added shell-level context rails, curriculum track snapshots, route-surface labels, and stronger next-step guidance across the homepage and main layout.",
    "11.0.0: Upgraded Study Hub with curriculum shelf summaries, stronger continuity cues, and better module orientation for broad-track browsing.",
    "11.0.0: Added Business Continuity Planner, Control Environment Review, Defective Contracts Classifier, and Business Case Analysis Planner.",
    "11.0.0: Added matching lesson modules, Smart Solver mappings, OCR routing rules, app catalog entries, and assignment-friendly workpaper templates for the new weak-track tools.",
    "10.1.0: Added Segmented Income Statement Analyzer and PERT Project Estimate Helper for managerial, responsibility-accounting, and operations coverage.",
    "10.1.0: Added Audit Sampling Planner, AIS Access Control Review Workspace, and RFBT Obligations and Contracts Issue Flow.",
    "10.1.0: Added FAR Quasi-Reorganization Deficit Cleanup and AFAR Corporate Liquidation Recovery Planner.",
    "10.1.0: Added Study Hub completion modules, Smart Solver matches, OCR routing rules, search catalog entries, and workpaper templates for all new tools.",
    "10.1.0: Added regression tests for new shared calculation helpers, discovery aliases, workpaper templates, and solve-target suggestions.",
    "10.1.0: Hardened Workpaper Studio narrow-screen editing, deferred live formula preview work, searchable template filtering, and idle-time autosave scheduling.",
    "10.1.0: Upgraded Confidence Interval Helper with z/t method selection and upgraded Capital Rationing Prioritizer with exact combination comparison.",
    "10.1.0: Added Activity-Based Costing, Financial Asset Amortized Cost, Investment Property Measurement, Joint Arrangement Share, and Quality Control Chart helpers with integrated lessons and workpapers.",
    "10.0.0: Added the library-driven expansion layer with DuPont, earnings quality, confidence intervals, retail pricing, capital rationing, provisions, and franchise revenue.",
] as const;
