export const APP_VERSION = "12.5.0";
export const APP_RELEASE_DATE = "2026-04-26";

export const APP_RELEASE_HIGHLIGHTS = [
    {
        title: "AccCalc 12.5.0 makes mobile navigation feel app-native",
        body: "The mobile menu now opens as a true viewport-owned panel with safe-area padding, internal scrolling, and no narrow card constraints.",
    },
    {
        title: "Settings now uses a full-screen mobile surface",
        body: "Settings no longer inherits the cramped side-sheet offsets on phones and tablets, so controls get the full available height and stay easier to scan.",
    },
    {
        title: "Overlay sizing is cleaner and safer",
        body: "Mobile overlays now own the viewport, respect notches and gesture areas internally, and avoid competing with sticky top chrome or the bottom navigation.",
    },
    {
        title: "Transient panel state is harder to confuse",
        body: "Opening menu, search, or settings now clears the other transient surfaces so users do not end up with stacked mobile panels after route or chrome changes.",
    },
    {
        title: "Panel scrolling is more reliable",
        body: "The shared body scroll lock still freezes the background, but now preserves vertical panning inside open overlay panels for long settings and navigation lists.",
    },
    {
        title: "The maintenance notes document the overlay contract",
        body: "README, release notes, system overview, and maintenance guidance now describe the full-screen mobile panel behavior and the viewport-token responsibilities.",
    },
] as const;

export const APP_RELEASE_NOTES = [
    "12.5.0: Reworked the mobile menu into a true full-screen viewport panel with safe-area padding, internal navigation scrolling, and no narrow drawer width cap.",
    "12.5.0: Reworked mobile settings into a full-screen panel for all non-desktop shell widths, removing side-sheet offsets, max-width constraints, and chrome-subtracted height math.",
    "12.5.0: Updated contextual page menus and mobile search overlay sizing so small-screen overlays use viewport-owned full-screen behavior instead of clipped page-remaining space.",
    "12.5.0: Tightened transient panel state so opening menu, search, or settings clears the other mobile surfaces instead of allowing awkward stacked overlay states.",
    "12.5.0: Adjusted the shared scroll lock to keep the background fixed while allowing vertical panning inside long overlay panels.",
    "12.5.0: Updated README, release notes, system overview, and maintenance guidance for the focused mobile overlay and shell reliability release.",
    "12.4.0: Added Audit Misstatement Evaluation Workspace, Segregation of Duties Conflict Matrix, and Governance Escalation Planner to strengthen weaker Audit, AIS, and Governance coverage with practical classroom decision tools.",
    "12.4.0: Added new FAR and managerial study topics for receivables estimation, cash discount discipline, cost behavior, and margin of safety, each with topic-specific quiz support and linked calculators.",
    "12.4.0: Tightened the lesson, quiz, and calculator loop so Study Hub topic cards, Practice Hub cards, weak-topic review panels, and quiz results now route students into the closest linked lesson or tool.",
    "12.4.0: Expanded Smart Solver and route discovery coverage for the new audit, AIS, and governance tools and sharpened segregation-of-duties prompts so they beat the broader access-control review when the prompt is really about incompatible duties.",
    "12.4.0: Expanded the theme system with palette-led families for Butter, Moss, Palm, Guava, Sunset, Sangria, Seabreeze, Lagoon, and Odyssey while preserving Classic as the default baseline.",
    "12.4.0: Reorganized Settings so Appearance now opens with a compact summary card, a smaller mode selector, a quick family strip, and a discoverable theme gallery instead of a large always-visible theme wall.",
    "12.4.0: Kept the earlier working theme families available so familiar Ocean, Slate, Rose, Blossom, Lavender, and Emerald selections continue to work alongside the newer palette families.",
    "12.4.0: Applied theme, family, contrast, motion, and meta theme-color state before React mounts to reduce visual flicker and make reload behavior more consistent.",
    "12.4.0: Strengthened the shared theme-token structure with cleaner family-driven chrome, accent, chip, chart, and workspace atmosphere variables.",
    "12.4.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the combined personalization and academic-expansion release.",
    "12.3.0: Rebuilt Smart Solver around topic-first routing so route families are classified before extraction and generic vocabulary no longer dominates calculator choice.",
    "12.3.0: Added route-family gating, contradiction pressure, and cleaner secondary-route separation so multi-concept prompts stop contaminating the primary prepared inputs.",
    "12.3.0: Moved Smart Solver UI summaries onto a selected-route source of truth so Best Match, confidence, interpreter feedback, prepared inputs, and open/apply actions stay aligned.",
    "12.3.0: Hardened extraction hygiene with stronger year/date, percent, and route-family field guards and improved intercompany transfer-price detection.",
    "12.3.0: Updated OCR parsing to use topic-first Smart Solver analysis, preserve comma-separated classroom amounts during normalization, and keep route-aware structured values cleaner before review.",
    "12.3.0: Added a reusable Smart Solver evaluation pack covering FAR, AFAR, Cost & Managerial, Audit, Tax, study-first, and OCR scenarios.",
    "12.3.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the Smart Solver and OCR precision release.",
    "12.2.0: Finished the shell viewport-fit pass by reserving top and bottom chrome space for page menus, mobile navigation, settings, search, and reminder overlays instead of letting temporary surfaces collide with app chrome.",
    "12.2.0: Removed redundant Learning Hub chrome so module shelves, recent lesson activity, and category browsing reach useful content faster with less label and chip noise.",
    "12.2.0: Rebuilt settings row layout rules with resilient grid and wrapping behavior so longer labels, selects, badges, and action buttons reflow cleanly on wider screens.",
    "12.2.0: Deferred disclosure body rendering, reduced repeated homepage status subscriptions, and trimmed low-value metadata so the app feels smoother during repeated daily use.",
    "12.2.0: Simplified shell context copy and page-menu framing so the focus-first system explains itself less and gets out of the user's way more often.",
    "12.2.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the shell-tightening and density-control release.",
    "12.1.0: Fixed the mobile menu root cause by portaling shell overlays to the viewport, removing shell clipping, and unifying live viewport-height handling for phones and small browsers.",
    "12.1.0: Added shared body-scroll locking so mobile navigation, settings, search, and page menus no longer compete with background scrolling or partial-screen overlays.",
    "12.1.0: Simplified the shell context rail and hid competing mobile chrome while transient panels are open, making navigation states clearer across phone, tablet, and desktop layouts.",
    "12.1.0: Reorganized the homepage around best-next surfaces, return flows, pinned tools, and delayed discovery instead of equal-weight content blocks.",
    "12.1.0: Moved lesson context into progressive disclosure and added a settings category map so reading and configuration flows stay more single-purpose.",
    "12.1.0: Updated README, release notes, system overview, maintenance guidance, and generated documentation for the stabilized focus-first release.",
    "12.0.0: Added a shared page menu system so secondary guidance, related study, and nearby routes stop crowding calculator and workspace headers.",
    "12.0.0: Reworked CalculatorPageLayout to keep inputs and results primary while moving supporting detail into progressive-disclosure surfaces.",
    "12.0.0: Rebuilt the homepage around next-step decisions, primary entry points, and delayed discovery instead of a broad feature wall.",
    "12.0.0: Reduced study-page side clutter by converting module flow and lesson signals into lighter on-demand references.",
    "12.0.0: Added Workpaper Studio focus mode so workbook health, context, and side utilities can move out of the editing path when needed.",
    "12.0.0: Updated release docs and maintenance guidance to formalize the focus-first page philosophy for future additions.",
    "11.0.0: Added shell-level context rails, curriculum track snapshots, route-surface labels, and stronger next-step guidance across the homepage and main layout.",
    "11.0.0: Upgraded Study Hub with curriculum shelf summaries, stronger continuity cues, and better module orientation for broad-track browsing.",
    "11.0.0: Added Business Continuity Planner, Control Environment Review, Defective Contracts Classifier, and Business Case Analysis Planner.",
    "11.0.0: Added matching lesson modules, Smart Solver mappings, OCR routing rules, app catalog entries, and assignment-friendly workpaper templates for the new weak-track tools.",
    "10.1.0: Added Segmented Income Statement Analyzer and PERT Project Estimate Helper for managerial, responsibility-accounting, and operations coverage.",
    "10.1.0: Added Audit Sampling Planner, AIS Access Control Review Workspace, and RFBT Obligations and Contracts Issue Flow.",
    "10.1.0: Added FAR Quasi-Reorganization Deficit Cleanup and AFAR Corporate Liquidation Recovery Planner.",
    "10.1.0: Added Study Hub completion modules, Smart Solver matches, OCR routing rules, search catalog entries, and workpaper templates for all new tools.",
    "10.1.0: Added regression tests for new shared calculation helpers, discovery aliases, workpaper templates, and solve-target suggestions.",
    "10.1.0: Hardened Workpaper Studio narrow-screen editing, deferred live formula preview work, searchable template filtering, and idle-time autosave scheduling.",
    "10.1.0: Upgraded Confidence Interval Helper with z/t method selection and upgraded Capital Rationing Prioritizer with exact combination comparison.",
    "10.1.0: Added Activity-Based Costing, Financial Asset Amortized Cost, Investment Property Measurement, Joint Arrangement Share, and Quality Control Chart helpers with integrated lessons and workpapers.",
    "10.0.0: Added the library-driven expansion layer with DuPont, earnings quality, confidence intervals, retail pricing, capital rationing, provisions, and franchise revenue.",
] as const;
