import type { WorkpaperCellRecord, WorkpaperTemplateDefinition } from "./workpaperTypes.js";
import {
    createCell,
    createEmptySheet,
    createWorkbook,
    getCellKey,
} from "./workpaperUtils.js";

function sheetCells(entries: Array<[number, number, string]>) {
    const cells: WorkpaperCellRecord = {};
    for (const [rowIndex, columnIndex, input] of entries) {
        cells[getCellKey(rowIndex, columnIndex)] = createCell(input);
    }
    return cells;
}

function headingCell(input: string) {
    return createCell(input, undefined, {
        bold: true,
        fillColor: "#DBEAFE",
        textColor: "#0F172A",
    });
}

function labelCell(input: string) {
    return createCell(input, undefined, {
        bold: true,
        fillColor: "#F8FAFC",
        textColor: "#0F172A",
    });
}

function buildSingleSheetTemplate(config: {
    title: string;
    description: string;
    topic: string;
    templateId: string;
    sheetTitle: string;
    rowCount: number;
    columnCount: number;
    note: string;
    tags: string[];
    relatedPaths: string[];
    entries: Array<[number, number, string]>;
}) {
    const baseCells = sheetCells(config.entries);
    if (!baseCells[getCellKey(0, 0)]) {
        baseCells[getCellKey(0, 0)] = headingCell(config.title);
    } else {
        baseCells[getCellKey(0, 0)] = headingCell(baseCells[getCellKey(0, 0)]?.input ?? config.title);
    }
    for (let columnIndex = 0; columnIndex < config.columnCount; columnIndex += 1) {
        const key = getCellKey(1, columnIndex);
        const existing = baseCells[key];
        if (existing?.input) {
            baseCells[key] = {
                ...existing,
                style: {
                    ...(existing.style ?? {}),
                    ...labelCell(existing.input).style,
                },
            };
        }
    }

    return {
        id: config.templateId,
        title: config.title,
        description: config.description,
        topic: config.topic,
        tags: config.tags,
        relatedPaths: config.relatedPaths,
        buildWorkbook: () =>
            createWorkbook({
                title: config.title,
                description: config.description,
                topic: config.topic,
                sheets: [
                    createEmptySheet({
                        title: config.sheetTitle,
                        kind: "template",
                        rowCount: config.rowCount,
                        columnCount: config.columnCount,
                        note: config.note,
                        templateId: config.templateId,
                        freezeRows: 2,
                        freezeColumns: 1,
                        cells: baseCells,
                    }),
                ],
            }),
    } satisfies WorkpaperTemplateDefinition;
}

export const WORKPAPER_TEMPLATES: WorkpaperTemplateDefinition[] = [
    buildSingleSheetTemplate({
        templateId: "cash-collections-schedule",
        title: "Cash Collections Schedule",
        description: "Collect period sales, lag rules, and total collections in one budget-support sheet.",
        topic: "Cost & Managerial",
        sheetTitle: "Collections Schedule",
        rowCount: 20,
        columnCount: 7,
        note: "Enter sales by period, then update collection rates or add supporting note rows underneath the schedule.",
        tags: ["budgeting", "cash collections", "receivables", "schedule"],
        relatedPaths: ["/business/cash-collections-schedule", "/business/cash-budget"],
        entries: [
            [0, 0, "Cash Collections Schedule"],
            [1, 0, "Period"],
            [1, 1, "Budgeted Sales"],
            [1, 2, "Current Collection"],
            [1, 3, "Lag 1 Collection"],
            [1, 4, "Lag 2 Collection"],
            [1, 5, "Beginning AR"],
            [1, 6, "Total Collections"],
            [2, 0, "Month 1"],
            [2, 6, "=SUM(B3:F3)"],
            [3, 0, "Month 2"],
            [3, 6, "=SUM(B4:F4)"],
            [4, 0, "Month 3"],
            [4, 6, "=SUM(B5:F5)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "cash-disbursements-schedule",
        title: "Cash Disbursements Schedule",
        description: "Track purchases, payment lags, and total cash outflows for budget planning.",
        topic: "Cost & Managerial",
        sheetTitle: "Disbursements Schedule",
        rowCount: 20,
        columnCount: 7,
        note: "Use payment-lag columns for purchases, payroll, and operating expense support as needed.",
        tags: ["budgeting", "cash disbursements", "payables", "schedule"],
        relatedPaths: ["/business/cash-disbursements-schedule", "/business/cash-budget"],
        entries: [
            [0, 0, "Cash Disbursements Schedule"],
            [1, 0, "Period"],
            [1, 1, "Purchases / Spend"],
            [1, 2, "Current Payment"],
            [1, 3, "Lag 1 Payment"],
            [1, 4, "Lag 2 Payment"],
            [1, 5, "Beginning AP"],
            [1, 6, "Total Payments"],
            [2, 0, "Month 1"],
            [2, 6, "=SUM(B3:F3)"],
            [3, 0, "Month 2"],
            [3, 6, "=SUM(B4:F4)"],
            [4, 0, "Month 3"],
            [4, 6, "=SUM(B5:F5)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "cash-budget-support",
        title: "Cash Budget Support Sheet",
        description: "Organize beginning cash, inflows, outflows, financing, and ending balance support.",
        topic: "Cost & Managerial",
        sheetTitle: "Cash Budget",
        rowCount: 24,
        columnCount: 6,
        note: "Use this sheet to bridge collections and disbursements into minimum-cash and financing decisions.",
        tags: ["cash budget", "budgeting", "planning"],
        relatedPaths: ["/business/cash-budget", "/business/cash-collections-schedule", "/business/cash-disbursements-schedule"],
        entries: [
            [0, 0, "Cash Budget Support"],
            [1, 0, "Line Item"],
            [1, 1, "Month 1"],
            [1, 2, "Month 2"],
            [1, 3, "Month 3"],
            [1, 4, "Quarter"],
            [2, 0, "Beginning Cash"],
            [3, 0, "Cash Collections"],
            [4, 0, "Total Cash Available"],
            [4, 1, "=B3+B4"],
            [4, 2, "=C3+C4"],
            [4, 3, "=D3+D4"],
            [5, 0, "Cash Disbursements"],
            [6, 0, "Financing"],
            [7, 0, "Ending Cash"],
            [7, 1, "=B5-B6+B7"],
            [7, 2, "=C5-C6+C7"],
            [7, 3, "=D5-D6+D7"],
            [7, 4, "=SUM(B8:D8)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "petty-cash-count-sheet",
        title: "Petty Cash Count Sheet",
        description: "Count cash, vouchers, stamps, and other accountable items before preparing a petty cash adjustment or replenishment entry.",
        topic: "Financial Accounting",
        sheetTitle: "Petty Cash Count",
        rowCount: 18,
        columnCount: 5,
        note: "Use the support section for coin breakdowns, voucher references, and short-or-over follow-up notes.",
        tags: ["petty cash", "cash control", "reconciliation", "workpaper"],
        relatedPaths: ["/accounting/petty-cash-reconciliation", "/accounting/bank-reconciliation"],
        entries: [
            [0, 0, "Petty Cash Count Sheet"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Imprest Fund"],
            [3, 0, "Cash on Hand"],
            [4, 0, "Petty Cash Vouchers"],
            [5, 0, "Stamps / Other Accountable Items"],
            [6, 0, "Other Receipts"],
            [7, 0, "Total Accounted For"],
            [7, 1, "=SUM(B4:B7)"],
            [8, 0, "Shortage (Overage)"],
            [8, 1, "=B8-B3"],
            [9, 0, "Replenishment Amount"],
            [9, 1, "=B3-B4"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "adjusting-entries-support",
        title: "Adjusting Entries Support Sheet",
        description: "Lay out beginning balances, ending balances, recognized amounts, and journal-entry effects for common accrual and deferral adjustments.",
        topic: "Financial Accounting",
        sheetTitle: "Adjusting Entries",
        rowCount: 22,
        columnCount: 6,
        note: "Prepaid and unearned rows are formula-supported. Accrued revenue and accrued expense rows stay open because class problems often mix earned or incurred amounts with ending receivable or payable balances.",
        tags: ["adjusting entries", "worksheet", "accruals", "deferrals"],
        relatedPaths: [
            "/accounting/adjusting-entries-workspace",
            "/accounting/prepaid-expense-adjustment",
            "/accounting/unearned-revenue-adjustment",
            "/accounting/accrued-revenue-adjustment",
            "/accounting/accrued-expense-adjustment",
        ],
        entries: [
            [0, 0, "Adjusting Entries Support"],
            [1, 0, "Topic"],
            [1, 1, "Beginning Balance"],
            [1, 2, "Ending Balance"],
            [1, 3, "Recognized This Period"],
            [1, 4, "Debit"],
            [1, 5, "Credit"],
            [2, 0, "Prepaid Expense"],
            [2, 3, "=B3-C3"],
            [3, 0, "Unearned Revenue"],
            [3, 3, "=B4-C4"],
            [4, 0, "Accrued Revenue"],
            [5, 0, "Accrued Expense"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "production-budget-support",
        title: "Production Budget Support Sheet",
        description: "Translate unit sales targets and finished-goods policy into required production units by period.",
        topic: "Cost & Managerial",
        sheetTitle: "Production Budget",
        rowCount: 18,
        columnCount: 6,
        note: "Add monthly or quarterly periods across the columns if you need a longer budget horizon.",
        tags: ["production budget", "manufacturing", "schedule", "budgeting"],
        relatedPaths: ["/business/production-budget", "/business/direct-materials-purchases-budget"],
        entries: [
            [0, 0, "Production Budget Support"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Quarter"],
            [2, 0, "Budgeted Sales Units"],
            [3, 0, "Desired Ending FG Units"],
            [4, 0, "Total Required Units"],
            [4, 1, "=B3+B4"],
            [4, 2, "=C3+C4"],
            [4, 3, "=D3+D4"],
            [5, 0, "Beginning FG Units"],
            [6, 0, "Required Production Units"],
            [6, 1, "=B5-B6"],
            [6, 2, "=C5-C6"],
            [6, 3, "=D5-D6"],
            [6, 4, "=SUM(B7:D7)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "direct-materials-purchases-support",
        title: "Direct Materials Purchases Budget Sheet",
        description: "Support materials required, desired ending materials, purchases, and budgeted purchase cost in one schedule.",
        topic: "Cost & Managerial",
        sheetTitle: "Materials Purchases",
        rowCount: 22,
        columnCount: 6,
        note: "Use the blank rows below for multiple materials, separate purchase prices, or policy notes.",
        tags: ["direct materials", "purchases budget", "manufacturing", "schedule"],
        relatedPaths: ["/business/direct-materials-purchases-budget", "/business/production-budget"],
        entries: [
            [0, 0, "Direct Materials Purchases Budget"],
            [1, 0, "Line Item"],
            [1, 1, "Units"],
            [1, 2, "Cost / Unit"],
            [1, 3, "Amount"],
            [2, 0, "Budgeted Production Units"],
            [3, 0, "Materials per Finished Unit"],
            [4, 0, "Materials Needed for Production"],
            [4, 1, "=B3*B4"],
            [5, 0, "Desired Ending Materials Units"],
            [6, 0, "Total Materials Required"],
            [6, 1, "=B5+B6"],
            [7, 0, "Beginning Materials Units"],
            [8, 0, "Materials to Purchase"],
            [8, 1, "=B7-B8"],
            [9, 0, "Material Cost per Unit"],
            [10, 0, "Budgeted Purchases Cost"],
            [10, 3, "=B9*C10"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "inventory-budget-support",
        title: "Inventory Budget Support Sheet",
        description: "Bridge budgeted cost of goods sold, inventory policy, and required merchandise purchases in one schedule.",
        topic: "Cost & Managerial",
        sheetTitle: "Inventory Budget",
        rowCount: 18,
        columnCount: 6,
        note: "Use one column per month or quarter when the assignment asks for a multi-period merchandise budget.",
        tags: ["inventory budget", "merchandising", "purchases budget", "schedule"],
        relatedPaths: ["/business/inventory-budget", "/business/cash-disbursements-schedule", "/business/cash-budget"],
        entries: [
            [0, 0, "Inventory Budget Support"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Quarter"],
            [2, 0, "Budgeted Cost of Goods Sold"],
            [3, 0, "Desired Ending Inventory"],
            [4, 0, "Total Goods Needed"],
            [4, 1, "=B3+B4"],
            [4, 2, "=C3+C4"],
            [4, 3, "=D3+D4"],
            [5, 0, "Beginning Inventory"],
            [6, 0, "Required Purchases"],
            [6, 1, "=B5-B6"],
            [6, 2, "=C5-C6"],
            [6, 3, "=D5-D6"],
            [6, 4, "=SUM(B7:D7)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "sales-budget-support",
        title: "Sales Budget Support Sheet",
        description: "Support budgeted unit sales, selling price, and total revenue in one starter schedule for master-budget work.",
        topic: "Cost & Managerial",
        sheetTitle: "Sales Budget",
        rowCount: 18,
        columnCount: 6,
        note: "Use one column per month or quarter when the assignment asks for a multi-period sales budget.",
        tags: ["sales budget", "master budget", "revenue planning", "schedule"],
        relatedPaths: ["/business/sales-budget", "/business/production-budget", "/business/cash-budget"],
        entries: [
            [0, 0, "Sales Budget Support"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Quarter"],
            [2, 0, "Budgeted Unit Sales"],
            [3, 0, "Selling Price / Unit"],
            [4, 0, "Budgeted Sales Revenue"],
            [4, 1, "=B3*B4"],
            [4, 2, "=C3*C4"],
            [4, 3, "=D3*D4"],
            [4, 4, "=SUM(B5:D5)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "operating-expense-budget-support",
        title: "Operating Expense Budget Sheet",
        description: "Support variable, fixed, total, and cash operating expenses for selling and administrative budgeting.",
        topic: "Cost & Managerial",
        sheetTitle: "Operating Expenses",
        rowCount: 20,
        columnCount: 6,
        note: "Keep non-cash expenses separate so the same sheet can support both the expense budget and the cash budget.",
        tags: ["operating expense budget", "selling and administrative", "cash planning", "schedule"],
        relatedPaths: ["/business/operating-expense-budget", "/business/cash-budget"],
        entries: [
            [0, 0, "Operating Expense Budget"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Quarter"],
            [2, 0, "Budgeted Sales"],
            [3, 0, "Variable Expense Rate"],
            [4, 0, "Variable Operating Expenses"],
            [4, 1, "=B3*B4"],
            [4, 2, "=C3*C4"],
            [4, 3, "=D3*D4"],
            [5, 0, "Fixed Operating Expenses"],
            [6, 0, "Total Operating Expenses"],
            [6, 1, "=B5+B6"],
            [6, 2, "=C5+C6"],
            [6, 3, "=D5+D6"],
            [7, 0, "Non-cash Expenses"],
            [8, 0, "Cash Operating Expenses"],
            [8, 1, "=B7-B8"],
            [8, 2, "=C7-C8"],
            [8, 3, "=D7-D8"],
            [8, 4, "=SUM(B9:D9)"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "vat-reconciliation-support",
        title: "VAT Reconciliation Workpaper",
        description: "Lay out taxable sales, vatable purchases, output VAT, input VAT, and the net remittance position in one tax-support sheet.",
        topic: "Taxation",
        sheetTitle: "VAT Reconciliation",
        rowCount: 18,
        columnCount: 4,
        note: "Use the lower rows for classification notes when some items are exempt, zero-rated, or outside the standard rate.",
        tags: ["vat", "tax", "reconciliation", "workpaper"],
        relatedPaths: ["/tax/vat-reconciliation", "/tax/percentage-tax", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "VAT Reconciliation Workpaper"],
            [1, 0, "Line Item"],
            [1, 1, "Base Amount"],
            [1, 2, "Rate"],
            [1, 3, "VAT Amount"],
            [2, 0, "Taxable Sales"],
            [3, 0, "Output VAT"],
            [3, 3, "=B3*C3"],
            [4, 0, "Vatable Purchases"],
            [5, 0, "Input VAT"],
            [5, 3, "=B5*C5"],
            [6, 0, "Net VAT Payable"],
            [6, 3, "=D4-D6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "intercompany-inventory-elimination-support",
        title: "Intercompany Inventory Elimination Sheet",
        description: "Support transfer price, markup basis, unsold portion, and unrealized profit for AFAR consolidation review.",
        topic: "AFAR",
        sheetTitle: "Inventory Elimination",
        rowCount: 18,
        columnCount: 5,
        note: "Use the notes rows for upstream versus downstream attribution and prior-period carryover issues.",
        tags: ["afar", "consolidation", "inventory elimination", "unrealized profit"],
        relatedPaths: ["/afar/intercompany-inventory-profit", "/afar/business-combination-analysis"],
        entries: [
            [0, 0, "Intercompany Inventory Elimination"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [1, 2, "Rate"],
            [1, 3, "Percent"],
            [1, 4, "Result"],
            [2, 0, "Transfer Price"],
            [3, 0, "Markup on Cost"],
            [4, 0, "Unsold at Period-End"],
            [5, 0, "Transferred Cost"],
            [6, 0, "Intercompany Gross Profit"],
            [7, 0, "Unrealized Profit"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "equity-rollforward-support",
        title: "Equity Rollforward Support Sheet",
        description: "Roll forward share capital, APIC, retained earnings, OCI, and treasury shares into ending equity support.",
        topic: "Financial Accounting",
        sheetTitle: "Equity Rollforward",
        rowCount: 20,
        columnCount: 5,
        note: "Use the last rows for disclosure notes on dividends, treasury-share activity, OCI components, or prior-period adjustments.",
        tags: ["equity", "statement of changes in equity", "financial statements", "workpaper"],
        relatedPaths: ["/far/statement-of-changes-in-equity-builder", "/far/retained-earnings-rollforward"],
        entries: [
            [0, 0, "Equity Rollforward Support"],
            [1, 0, "Component"],
            [1, 1, "Beginning"],
            [1, 2, "Changes"],
            [1, 3, "Ending"],
            [1, 4, "Notes"],
            [2, 0, "Share Capital"],
            [3, 0, "Additional Paid-in Capital"],
            [4, 0, "Retained Earnings"],
            [5, 0, "Accumulated OCI"],
            [6, 0, "Treasury Shares"],
            [7, 0, "Total Equity"],
            [7, 1, "=SUM(B3:B6)-B7"],
            [7, 3, "=SUM(D3:D6)-D7"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "ratio-summary",
        title: "Ratio Summary Workpaper",
        description: "Record formulas, raw amounts, and interpretation notes for ratio analysis.",
        topic: "Strategic & Integrative",
        sheetTitle: "Ratio Summary",
        rowCount: 24,
        columnCount: 6,
        note: "Use the notes section under the grid for interpretation, trend reading, and peer comparison comments.",
        tags: ["ratio analysis", "financial analysis", "statement analysis"],
        relatedPaths: ["/accounting/ratio-analysis-workspace", "/accounting/common-size-income-statement"],
        entries: [
            [0, 0, "Ratio Summary Sheet"],
            [1, 0, "Ratio"],
            [1, 1, "Formula"],
            [1, 2, "Current Year"],
            [1, 3, "Prior Year"],
            [1, 4, "Variance"],
            [1, 5, "Interpretation"],
            [2, 0, "Current Ratio"],
            [3, 0, "Quick Ratio"],
            [4, 0, "Gross Margin"],
            [5, 0, "Return on Assets"],
            [6, 0, "Receivables Turnover"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "inventory-planning",
        title: "Inventory Planning Sheet",
        description: "Combine demand assumptions, reorder planning, lead times, and safety-stock support.",
        topic: "Operations & Supply Chain",
        sheetTitle: "Inventory Planning",
        rowCount: 20,
        columnCount: 7,
        note: "Best used with EOQ, reorder point, and inventory-control review workflows.",
        tags: ["inventory", "operations", "eoq", "reorder point"],
        relatedPaths: ["/operations/eoq-and-reorder-point", "/accounting/inventory-control-workspace"],
        entries: [
            [0, 0, "Inventory Planning Sheet"],
            [1, 0, "Item"],
            [1, 1, "Annual Demand"],
            [1, 2, "Order Cost"],
            [1, 3, "Holding Cost"],
            [1, 4, "Lead Time (days)"],
            [1, 5, "Safety Stock"],
            [1, 6, "Reorder Point"],
            [2, 0, "SKU A"],
            [2, 6, "=((B3/365)*E3)+F3"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "cvp-analysis",
        title: "CVP Analysis Workpaper",
        description: "Lay out contribution margin, break-even, target profit, and sensitivity support in one worksheet.",
        topic: "Cost & Managerial",
        sheetTitle: "CVP Workpaper",
        rowCount: 22,
        columnCount: 6,
        note: "This template works well for classroom solve-check-revise cycles and managerial planning comparisons.",
        tags: ["cvp", "break-even", "target profit", "managerial"],
        relatedPaths: ["/business/cvp-analysis", "/business/target-profit", "/business/margin-of-safety"],
        entries: [
            [0, 0, "CVP Analysis Workpaper"],
            [1, 0, "Input"],
            [1, 1, "Amount"],
            [2, 0, "Fixed Costs"],
            [3, 0, "Selling Price / Unit"],
            [4, 0, "Variable Cost / Unit"],
            [5, 0, "Contribution Margin / Unit"],
            [5, 1, "=B4-B5"],
            [6, 0, "Break-even Units"],
            [6, 1, "=B3/B6"],
            [7, 0, "Target Profit"],
            [8, 0, "Required Units"],
            [8, 1, "=(B3+B8)/B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "capital-budgeting-comparison",
        title: "Capital Budgeting Comparison",
        description: "Compare project cash flows, NPV, PI, payback, and recommendation notes.",
        topic: "Finance / Econ / Math",
        sheetTitle: "Capital Budgeting",
        rowCount: 20,
        columnCount: 7,
        note: "Keep assumptions, hurdle rate notes, and ranking rationale in the lower part of the sheet.",
        tags: ["capital budgeting", "npv", "irr", "payback"],
        relatedPaths: ["/finance/capital-budgeting-comparison", "/finance/npv", "/finance/internal-rate-of-return"],
        entries: [
            [0, 0, "Capital Budgeting Comparison"],
            [1, 0, "Metric"],
            [1, 1, "Project A"],
            [1, 2, "Project B"],
            [1, 3, "Project C"],
            [2, 0, "Initial Investment"],
            [3, 0, "NPV"],
            [4, 0, "IRR"],
            [5, 0, "PI"],
            [6, 0, "Discounted Payback"],
            [7, 0, "Recommendation"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "retained-earnings-rollforward",
        title: "Retained Earnings Rollforward",
        description: "Track beginning retained earnings, current-period profit, dividends, and ending balance support.",
        topic: "FAR",
        sheetTitle: "Retained Earnings",
        rowCount: 18,
        columnCount: 5,
        note: "Use this for statement-of-changes-in-equity support, dividend questions, and retained-earnings reconciliation work.",
        tags: ["equity", "retained earnings", "dividends", "far"],
        relatedPaths: ["/far/retained-earnings-rollforward"],
        entries: [
            [0, 0, "Retained Earnings Rollforward"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Beginning Retained Earnings"],
            [3, 0, "Net Income"],
            [4, 0, "Prior Period Adjustment"],
            [5, 0, "Dividends Declared"],
            [6, 0, "Ending Retained Earnings"],
            [6, 1, "=B3+B4+B5-B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "business-tax-review",
        title: "Business Tax Review Sheet",
        description: "Organize taxable sales, rates, VAT-versus-percentage-tax notes, and filing reminders in one support sheet.",
        topic: "Taxation",
        sheetTitle: "Business Tax",
        rowCount: 18,
        columnCount: 6,
        note: "Useful for reviewing whether a problem belongs to VAT, percentage tax, or another business-tax track before computing the answer.",
        tags: ["tax", "percentage tax", "vat", "business taxation"],
        relatedPaths: ["/tax/percentage-tax", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "Business Tax Review"],
            [1, 0, "Item"],
            [1, 1, "Amount / Rate"],
            [1, 2, "Base"],
            [1, 3, "Tax Due"],
            [1, 4, "Regime"],
            [1, 5, "Notes"],
            [2, 0, "Percentage Tax"],
            [3, 0, "VAT"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "afn-forecast-support",
        title: "AFN Forecast Support",
        description: "Lay out sales growth, asset support, spontaneous liabilities, retained earnings support, and the outside financing gap.",
        topic: "Cost & Managerial",
        sheetTitle: "AFN Forecast",
        rowCount: 20,
        columnCount: 5,
        note: "Use this when you need to explain where the financing gap comes from instead of showing only the final AFN number.",
        tags: ["afn", "forecasting", "planning", "financing"],
        relatedPaths: ["/business/additional-funds-needed"],
        entries: [
            [0, 0, "AFN Forecast Support"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Current Sales"],
            [3, 0, "Projected Sales"],
            [4, 0, "Change in Sales"],
            [4, 1, "=B4-B3"],
            [5, 0, "Required Asset Increase"],
            [6, 0, "Spontaneous Liability Support"],
            [7, 0, "Internal Financing"],
            [8, 0, "Additional Funds Needed"],
            [8, 1, "=B6-B7-B8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "audit-planning",
        title: "Audit Planning Workpaper",
        description: "Capture engagement objectives, risks, materiality, procedures, and staffing support.",
        topic: "Audit & Assurance",
        sheetTitle: "Audit Planning",
        rowCount: 24,
        columnCount: 6,
        note: "Use rows below the main matrix for control-risk notes, fraud risk factors, and timing decisions.",
        tags: ["audit", "planning", "materiality", "risk"],
        relatedPaths: ["/audit/audit-planning-workspace", "/audit/audit-cycle-reviewer"],
        entries: [
            [0, 0, "Audit Planning Workpaper"],
            [1, 0, "Area / Cycle"],
            [1, 1, "Assertion Focus"],
            [1, 2, "Risk Rating"],
            [1, 3, "Materiality Link"],
            [1, 4, "Planned Procedure"],
            [1, 5, "Notes"],
            [2, 0, "Revenue and Collection"],
            [3, 0, "Expenditure"],
            [4, 0, "Inventory / Conversion"],
            [5, 0, "Investing / Financing"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "risk-control-matrix",
        title: "Risk and Control Matrix",
        description: "Document risks, controls, gaps, owners, and follow-up actions in a reusable matrix.",
        topic: "Governance & Ethics",
        sheetTitle: "Risk Control Matrix",
        rowCount: 24,
        columnCount: 7,
        note: "Pair this with audit planning, AIS control reviews, and governance lessons for integrative use.",
        tags: ["risk", "control", "governance", "matrix"],
        relatedPaths: ["/governance/risk-control-matrix", "/ais/it-control-matrix"],
        entries: [
            [0, 0, "Risk and Control Matrix"],
            [1, 0, "Process"],
            [1, 1, "Risk"],
            [1, 2, "Control"],
            [1, 3, "Control Owner"],
            [1, 4, "Assessment"],
            [1, 5, "Gap / Issue"],
            [1, 6, "Action"],
            [2, 0, "Cash Handling"],
            [3, 0, "Revenue Recognition"],
            [4, 0, "User Access"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "tax-difference-bridge",
        title: "Book-Tax Difference Bridge",
        description: "Track permanent and temporary differences with supporting tax effect notes.",
        topic: "Taxation",
        sheetTitle: "Book-Tax Bridge",
        rowCount: 22,
        columnCount: 6,
        note: "This template works well for tax-compliance review and accounting-vs-tax comparison problems.",
        tags: ["tax", "book tax difference", "temporary differences"],
        relatedPaths: ["/tax/book-tax-difference-workspace", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "Book-Tax Difference Bridge"],
            [1, 0, "Difference"],
            [1, 1, "Book Amount"],
            [1, 2, "Tax Amount"],
            [1, 3, "Difference"],
            [1, 4, "Type"],
            [1, 5, "Tax Effect Note"],
            [2, 0, "Depreciation"],
            [3, 0, "Estimated Warranty"],
            [4, 0, "Non-deductible Expense"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "direct-labor-budget-support",
        title: "Direct Labor Budget Sheet",
        description: "Support production units, labor hours, hourly rates, and total direct labor cost in one schedule.",
        topic: "Cost & Managerial",
        sheetTitle: "Direct Labor Budget",
        rowCount: 18,
        columnCount: 6,
        note: "Use separate rows for departments or skill groups when the assignment uses more than one labor rate.",
        tags: ["direct labor", "budgeting", "manufacturing", "schedule"],
        relatedPaths: ["/business/direct-labor-budget", "/business/production-budget"],
        entries: [
            [0, 0, "Direct Labor Budget"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Quarter"],
            [2, 0, "Budgeted Production Units"],
            [3, 0, "Labor Hours per Unit"],
            [4, 0, "Total Labor Hours"],
            [4, 1, "=B3*B4"],
            [5, 0, "Labor Rate per Hour"],
            [6, 0, "Total Direct Labor Cost"],
            [6, 1, "=B5*B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "factory-overhead-budget-support",
        title: "Factory Overhead Budget Sheet",
        description: "Separate variable and fixed factory overhead for master-budget and performance-report support.",
        topic: "Cost & Managerial",
        sheetTitle: "Factory Overhead",
        rowCount: 18,
        columnCount: 6,
        note: "Keep depreciation or other non-cash overhead visible if the next step is a cash budget or flexible-budget comparison.",
        tags: ["factory overhead", "manufacturing overhead", "budgeting"],
        relatedPaths: ["/business/factory-overhead-budget", "/accounting/factory-overhead-variance"],
        entries: [
            [0, 0, "Factory Overhead Budget"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Budgeted Activity Units"],
            [3, 0, "Variable OH Rate / Unit"],
            [4, 0, "Variable OH Budget"],
            [4, 1, "=B3*B4"],
            [5, 0, "Fixed OH Budget"],
            [6, 0, "Total Factory OH Budget"],
            [6, 1, "=B5+B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "budgeted-income-statement-support",
        title: "Budgeted Income Statement Support",
        description: "Bridge budgeted sales, COGS, operating expenses, interest, and tax into a clean projected income statement.",
        topic: "Cost & Managerial",
        sheetTitle: "Budgeted Income Statement",
        rowCount: 18,
        columnCount: 5,
        note: "Use this after the supporting sales, production, labor, overhead, and operating-expense schedules are complete.",
        tags: ["budgeted income statement", "pro forma", "master budget"],
        relatedPaths: ["/business/budgeted-income-statement", "/business/operating-expense-budget"],
        entries: [
            [0, 0, "Budgeted Income Statement"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Budgeted Sales"],
            [3, 0, "Budgeted COGS"],
            [4, 0, "Gross Profit"],
            [4, 1, "=B3-B4"],
            [5, 0, "Operating Expenses"],
            [6, 0, "Interest Expense"],
            [7, 0, "Income Before Tax"],
            [7, 1, "=B5-B6-B7"],
            [8, 0, "Income Tax Expense"],
            [9, 0, "Net Income"],
            [9, 1, "=B8-B9"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "notes-receivable-discounting-support",
        title: "Notes Receivable Discounting Sheet",
        description: "Track note face amount, maturity value, bank discount, and proceeds when a note is discounted.",
        topic: "Financial Accounting",
        sheetTitle: "Note Discounting",
        rowCount: 16,
        columnCount: 5,
        note: "Adjust the time basis if the classroom problem uses exact days instead of a simple year fraction.",
        tags: ["notes receivable", "discounting", "bank discount"],
        relatedPaths: ["/accounting/notes-receivable-discounting", "/accounting/notes-interest"],
        entries: [
            [0, 0, "Notes Receivable Discounting"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Face Value"],
            [3, 0, "Note Interest"],
            [4, 0, "Maturity Value"],
            [4, 1, "=B3+B4"],
            [5, 0, "Bank Discount"],
            [6, 0, "Proceeds"],
            [6, 1, "=B5-B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "equity-method-rollforward",
        title: "Equity Method Rollforward",
        description: "Roll forward an associate investment through share in income and dividends.",
        topic: "AFAR",
        sheetTitle: "Equity Method",
        rowCount: 16,
        columnCount: 5,
        note: "Add extra rows below if the assignment includes acquisition-date excess, amortization, or impairment adjustments.",
        tags: ["equity method", "associate", "investment rollforward"],
        relatedPaths: ["/afar/equity-method-investment", "/afar/business-combination-analysis"],
        entries: [
            [0, 0, "Equity Method Rollforward"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Beginning Investment"],
            [3, 0, "Share in Income"],
            [4, 0, "Dividends Received"],
            [5, 0, "Ending Investment"],
            [5, 1, "=B3+B4-B5"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "intercompany-ppe-transfer-support",
        title: "Intercompany PPE Transfer Sheet",
        description: "Support unrealized gain, excess depreciation, and remaining intercompany profit for AFAR elimination review.",
        topic: "AFAR",
        sheetTitle: "PPE Transfer",
        rowCount: 16,
        columnCount: 5,
        note: "This template assumes straight-line depreciation over the remaining useful life unless the case says otherwise.",
        tags: ["intercompany ppe", "consolidation", "excess depreciation"],
        relatedPaths: ["/afar/intercompany-ppe-transfer", "/afar/intercompany-inventory-profit"],
        entries: [
            [0, 0, "Intercompany PPE Transfer"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Transfer Price"],
            [3, 0, "Seller Carrying Amount"],
            [4, 0, "Unrealized Gain"],
            [4, 1, "=B3-B4"],
            [5, 0, "Annual Excess Depreciation"],
            [6, 0, "Recognized to Date"],
            [7, 0, "Unamortized Intercompany Profit"],
            [7, 1, "=B5-B7"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "special-order-decision-support",
        title: "Special Order Decision Sheet",
        description: "Lay out incremental revenue, incremental cost, and minimum acceptable price for special-order analysis.",
        topic: "Cost & Managerial",
        sheetTitle: "Special Order",
        rowCount: 16,
        columnCount: 5,
        note: "Keep unused fixed costs out of the relevant-cost section unless the case explicitly says they change.",
        tags: ["special order", "relevant costing", "decision making"],
        relatedPaths: ["/business/special-order-analysis", "/business/make-or-buy-analysis"],
        entries: [
            [0, 0, "Special Order Decision"],
            [1, 0, "Line Item"],
            [1, 1, "Units"],
            [1, 2, "Price / Cost"],
            [1, 3, "Amount"],
            [2, 0, "Special Order Units"],
            [3, 0, "Special Order Price / Unit"],
            [4, 0, "Incremental Revenue"],
            [4, 3, "=B3*C4"],
            [5, 0, "Variable Cost / Unit"],
            [6, 0, "Incremental Variable Cost"],
            [6, 3, "=B3*C6"],
            [7, 0, "Incremental Fixed Cost"],
            [8, 0, "Incremental Profit"],
            [8, 3, "=D5-D7-D8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "make-or-buy-support",
        title: "Make or Buy Decision Sheet",
        description: "Support relevant make cost, relevant buy cost, and the indifference buy price in one sourcing worksheet.",
        topic: "Cost & Managerial",
        sheetTitle: "Make or Buy",
        rowCount: 16,
        columnCount: 5,
        note: "Only avoidable fixed costs belong in the make side of the comparison.",
        tags: ["make or buy", "outsourcing", "relevant costing"],
        relatedPaths: ["/business/make-or-buy-analysis", "/business/special-order-analysis"],
        entries: [
            [0, 0, "Make or Buy Decision"],
            [1, 0, "Line Item"],
            [1, 1, "Units"],
            [1, 2, "Rate / Cost"],
            [1, 3, "Amount"],
            [2, 0, "Units Needed"],
            [3, 0, "Variable Make Cost / Unit"],
            [4, 0, "Relevant Make Cost"],
            [4, 3, "=B3*C4"],
            [5, 0, "Avoidable Fixed Costs"],
            [6, 0, "Total Make Cost"],
            [6, 3, "=D5+D6"],
            [7, 0, "Buy Price / Unit"],
            [8, 0, "Total Buy Cost"],
            [8, 3, "=B3*C8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "sell-or-process-further-support",
        title: "Sell or Process Further Sheet",
        description: "Separate split-off value, added revenue, separable cost, and the incremental gain from further processing.",
        topic: "Cost & Managerial",
        sheetTitle: "Process Further",
        rowCount: 16,
        columnCount: 5,
        note: "Joint cost before split-off stays outside the incremental comparison.",
        tags: ["sell or process further", "split-off", "joint products"],
        relatedPaths: ["/business/sell-or-process-further", "/business/special-order-analysis"],
        entries: [
            [0, 0, "Sell or Process Further"],
            [1, 0, "Line Item"],
            [1, 1, "Units"],
            [1, 2, "Per Unit"],
            [1, 3, "Amount"],
            [2, 0, "Units"],
            [3, 0, "Split-off Value / Unit"],
            [4, 0, "After-Processing Price / Unit"],
            [5, 0, "Incremental Revenue"],
            [5, 3, "=B3*(C5-C4)"],
            [6, 0, "Separable Cost / Unit"],
            [7, 0, "Separable Processing Cost"],
            [7, 3, "=B3*C7"],
            [8, 0, "Incremental Profit"],
            [8, 3, "=D6-D8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "constrained-resource-product-mix-support",
        title: "Constrained Resource Product Mix Sheet",
        description: "Rank products by contribution margin per scarce-resource unit and estimate output supported by the bottleneck.",
        topic: "Cost & Managerial",
        sheetTitle: "Product Mix",
        rowCount: 18,
        columnCount: 6,
        note: "Duplicate the product rows below when you need to compare several products in one bottleneck analysis.",
        tags: ["product mix", "constraint", "management services"],
        relatedPaths: ["/business/constrained-resource-product-mix", "/business/cvp-analysis"],
        entries: [
            [0, 0, "Constrained Resource Product Mix"],
            [1, 0, "Line Item"],
            [1, 1, "Selling Price"],
            [1, 2, "Variable Cost"],
            [1, 3, "CM / Unit"],
            [1, 4, "Constraint / Unit"],
            [1, 5, "CM / Constraint Unit"],
            [2, 0, "Product A"],
            [2, 3, "=B3-C3"],
            [2, 5, "=D3/E3"],
            [3, 0, "Available Constraint Units"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "transfer-pricing-support",
        title: "Transfer Pricing Support Sheet",
        description: "Lay out variable cost, opportunity cost, outside market price, and the resulting internal transfer-pricing range.",
        topic: "Cost & Managerial",
        sheetTitle: "Transfer Pricing",
        rowCount: 16,
        columnCount: 4,
        note: "Use this sheet to show whether an internal transfer-pricing band exists before debating the final negotiated price.",
        tags: ["transfer pricing", "divisional performance", "managerial"],
        relatedPaths: [
            "/business/transfer-pricing-support",
            "/business/make-or-buy-analysis",
            "/business/constrained-resource-product-mix",
        ],
        entries: [
            [0, 0, "Transfer Pricing Support"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Variable Cost / Unit"],
            [3, 0, "Opportunity Cost / Unit"],
            [4, 0, "Minimum Transfer Price"],
            [4, 1, "=B3+B4"],
            [5, 0, "Outside Market Price / Unit"],
            [6, 0, "Negotiation Range Width"],
            [6, 1, "=B6-B5"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "budget-variance-analysis-support",
        title: "Budget Variance Analysis Sheet",
        description: "Lay out actual, flexible-budget, and static-budget amounts with spending and activity variance follow-through.",
        topic: "Cost & Managerial",
        sheetTitle: "Variance Analysis",
        rowCount: 16,
        columnCount: 4,
        note: "Use one row per cost or revenue line when the assignment requires a fuller performance report.",
        tags: ["budget variance", "performance report", "flexible budget"],
        relatedPaths: ["/business/budget-variance-analysis", "/business/flexible-budget"],
        entries: [
            [0, 0, "Budget Variance Analysis"],
            [1, 0, "Line Item"],
            [1, 1, "Actual"],
            [1, 2, "Flexible"],
            [1, 3, "Static"],
            [2, 0, "Amount"],
            [3, 0, "Spending Variance"],
            [3, 1, "=B3-C3"],
            [4, 0, "Activity Variance"],
            [4, 1, "=C3-D3"],
            [5, 0, "Total Variance"],
            [5, 1, "=B3-D3"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "moving-average-forecast-support",
        title: "Moving Average Forecast Sheet",
        description: "Support simple and weighted moving-average demand forecasting from recent periods and explicit weights.",
        topic: "Operations & Supply Chain",
        sheetTitle: "Forecast",
        rowCount: 16,
        columnCount: 5,
        note: "Adjust the weights only when you can explain why the recent periods deserve more or less influence.",
        tags: ["forecasting", "moving average", "operations"],
        relatedPaths: ["/operations/moving-average-forecast", "/operations/eoq-and-reorder-point"],
        entries: [
            [0, 0, "Moving Average Forecast"],
            [1, 0, "Line Item"],
            [1, 1, "Period 1"],
            [1, 2, "Period 2"],
            [1, 3, "Period 3"],
            [1, 4, "Next Forecast"],
            [2, 0, "Demand"],
            [3, 0, "Weight"],
            [4, 0, "Simple Average"],
            [4, 4, "=AVERAGE(B3:D3)"],
            [5, 0, "Weighted Average"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "sales-volume-variance-support",
        title: "Sales Volume Variance Sheet",
        description: "Support actual-versus-budgeted unit volume analysis using the budgeted contribution margin per unit.",
        topic: "Cost & Managerial",
        sheetTitle: "Sales Volume",
        rowCount: 14,
        columnCount: 4,
        note: "Keep the contribution margin per unit on a budgeted basis so the variance stays focused on volume, not pricing changes.",
        tags: ["sales volume variance", "sales quantity variance", "managerial"],
        relatedPaths: ["/business/sales-volume-variance", "/business/sales-mix-variance"],
        entries: [
            [0, 0, "Sales Volume Variance"],
            [1, 0, "Line Item"],
            [1, 1, "Units / Amount"],
            [2, 0, "Actual Units Sold"],
            [3, 0, "Budgeted Units Sold"],
            [4, 0, "Unit Difference"],
            [4, 1, "=B3-B4"],
            [5, 0, "Budgeted CM / Unit"],
            [6, 0, "Sales Volume Variance"],
            [6, 1, "=B5*B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "sales-mix-variance-support",
        title: "Sales Mix Variance Sheet",
        description: "Support actual-versus-budgeted mix analysis using actual total volume and budgeted contribution margin per unit.",
        topic: "Cost & Managerial",
        sheetTitle: "Sales Mix",
        rowCount: 16,
        columnCount: 4,
        note: "Use one sheet per product when you want to isolate how each product's actual mix differed from the plan.",
        tags: ["sales mix variance", "mix variance", "managerial"],
        relatedPaths: ["/business/sales-mix-variance", "/business/sales-volume-variance"],
        entries: [
            [0, 0, "Sales Mix Variance"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Actual Total Units Sold"],
            [3, 0, "Actual Product Units Sold"],
            [4, 0, "Actual Mix %"],
            [4, 1, "=B4/B3"],
            [5, 0, "Budgeted Mix %"],
            [6, 0, "Equivalent Unit Difference"],
            [6, 1, "=B3*(B5-B6)"],
            [7, 0, "Budgeted CM / Unit"],
            [8, 0, "Sales Mix Variance"],
            [8, 1, "=B7*B8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "safety-stock-and-reorder-support",
        title: "Safety Stock and Reorder Sheet",
        description: "Lay out average and maximum demand plus lead time to support safety stock and reorder-point policy.",
        topic: "Operations & Supply Chain",
        sheetTitle: "Safety Stock",
        rowCount: 16,
        columnCount: 4,
        note: "Keep average and worst-case assumptions visible so the reorder point is easy to defend in class discussion.",
        tags: ["safety stock", "reorder point", "operations"],
        relatedPaths: ["/operations/safety-stock-planner", "/operations/eoq-and-reorder-point"],
        entries: [
            [0, 0, "Safety Stock Planner"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Average Daily Usage"],
            [3, 0, "Maximum Daily Usage"],
            [4, 0, "Average Lead Time (days)"],
            [5, 0, "Maximum Lead Time (days)"],
            [6, 0, "Max Usage During Lead Time"],
            [6, 1, "=B4*B6"],
            [7, 0, "Average Usage During Lead Time"],
            [7, 1, "=B3*B5"],
            [8, 0, "Safety Stock"],
            [8, 1, "=B7-B8"],
            [9, 0, "Reorder Point"],
            [9, 1, "=B8+B9"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "estate-tax-support",
        title: "Estate Tax Support Sheet",
        description: "Support gross estate, deductions, taxable base, and estate tax due with visible rate assumptions.",
        topic: "Taxation",
        sheetTitle: "Estate Tax",
        rowCount: 14,
        columnCount: 4,
        note: "Keep the tax-rate assumption on the sheet so the classroom or jurisdictional basis stays visible.",
        tags: ["estate tax", "transfer tax", "taxation"],
        relatedPaths: ["/tax/estate-tax-helper", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "Estate Tax Support"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Gross Estate"],
            [3, 0, "Allowable Deductions"],
            [4, 0, "Net Estate"],
            [4, 1, "=B3-B4"],
            [5, 0, "Tax Rate %"],
            [6, 0, "Estate Tax Due"],
            [6, 1, "=B5*B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "donors-tax-support",
        title: "Donor's Tax Support Sheet",
        description: "Support gross gift, taxable gift, and donor's tax due with visible rate assumptions.",
        topic: "Taxation",
        sheetTitle: "Donor Tax",
        rowCount: 14,
        columnCount: 4,
        note: "Add a line for exemption or non-taxable transfer support if your class problem requires it.",
        tags: ["donor's tax", "gift tax", "taxation"],
        relatedPaths: ["/tax/donors-tax-helper", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "Donor's Tax Support"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Gross Gift"],
            [3, 0, "Exemption / Non-Taxable Portion"],
            [4, 0, "Taxable Gift"],
            [4, 1, "=B3-B4"],
            [5, 0, "Tax Rate %"],
            [6, 0, "Donor's Tax Due"],
            [6, 1, "=B5*B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "documentary-stamp-tax-support",
        title: "Documentary Stamp Tax Sheet",
        description: "Support taxable base conversion into taxable units and compute documentary stamp tax due.",
        topic: "Taxation",
        sheetTitle: "DST",
        rowCount: 14,
        columnCount: 4,
        note: "Use ceiling treatment on taxable units when the applicable classroom rule requires rounding up.",
        tags: ["documentary stamp tax", "dst", "taxation"],
        relatedPaths: ["/tax/documentary-stamp-tax-helper", "/tax/tax-compliance-review"],
        entries: [
            [0, 0, "Documentary Stamp Tax Support"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Taxable Base Amount"],
            [3, 0, "Taxable Unit Size"],
            [4, 0, "Taxable Units"],
            [4, 1, "=ROUNDUP(B3/B4,0)"],
            [5, 0, "Rate per Unit"],
            [6, 0, "DST Due"],
            [6, 1, "=B5*B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "consignment-settlement-support",
        title: "Consignment Settlement Sheet",
        description: "Lay out sales, commission, reimbursable expenses, advances, and the final balance still due to the consignor.",
        topic: "AFAR",
        sheetTitle: "Consignment",
        rowCount: 16,
        columnCount: 4,
        note: "Treat the sheet like a remittance statement so the settlement stays easy to audit.",
        tags: ["consignment", "consignee", "afar"],
        relatedPaths: ["/afar/consignment-settlement", "/afar/branch-inventory-loading"],
        entries: [
            [0, 0, "Consignment Settlement"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Sales"],
            [3, 0, "Commission Rate %"],
            [4, 0, "Commission Amount"],
            [4, 1, "=B3*B4"],
            [5, 0, "Freight and Other Expenses"],
            [6, 0, "Advances Remitted"],
            [7, 0, "Cash Still Due to Consignor"],
            [7, 1, "=B3-B5-B6-B7"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "branch-inventory-loading-support",
        title: "Branch Inventory Loading Sheet",
        description: "Support loading-rate conversion, allowance for overvaluation, and branch inventory at cost.",
        topic: "AFAR",
        sheetTitle: "Branch Loading",
        rowCount: 15,
        columnCount: 4,
        note: "Use this when the problem presents branch inventory at billed price and asks for the home-office cost view.",
        tags: ["branch inventory", "loading", "afar"],
        relatedPaths: ["/afar/branch-inventory-loading", "/afar/consignment-settlement"],
        entries: [
            [0, 0, "Branch Inventory Loading"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Billed Price Inventory"],
            [3, 0, "Loading on Cost %"],
            [4, 0, "Loading Rate on Billed Price %"],
            [4, 1, "=B4/(100+B4)"],
            [5, 0, "Allowance for Overvaluation"],
            [5, 1, "=B3*B5"],
            [6, 0, "Inventory at Cost"],
            [6, 1, "=B3-B6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "dividend-allocation-support",
        title: "Dividend Allocation Sheet",
        description: "Support preferred dividend priority, arrears, common allocation, and common dividend per share.",
        topic: "FAR",
        sheetTitle: "Dividend Allocation",
        rowCount: 18,
        columnCount: 4,
        note: "Keep preferred-share rights visible so the common-share allocation is easy to explain.",
        tags: ["dividends", "preferred shares", "far"],
        relatedPaths: ["/far/dividend-allocation", "/far/retained-earnings-rollforward"],
        entries: [
            [0, 0, "Dividend Allocation"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Total Dividends Declared"],
            [3, 0, "Preferred Shares"],
            [4, 0, "Preferred Par Value"],
            [5, 0, "Preferred Dividend Rate %"],
            [6, 0, "Years in Arrears"],
            [7, 0, "Preferred Dividend Allocation"],
            [8, 0, "Common Dividend Allocation"],
            [9, 0, "Common Shares Outstanding"],
            [10, 0, "Common Dividend per Share"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "borrowing-costs-capitalization-support",
        title: "Borrowing Costs Capitalization Sheet",
        description: "Support weighted expenditures, capitalization rate, capitalization period, and avoidable borrowing cost on one FAR workpaper.",
        topic: "FAR",
        sheetTitle: "Borrowing Costs",
        rowCount: 16,
        columnCount: 4,
        note: "Keep the capitalization-period assumption visible so the avoidable-interest result can be defended in class discussion.",
        tags: ["borrowing costs", "qualifying asset", "far"],
        relatedPaths: ["/far/borrowing-costs-capitalization", "/far/asset-disposal-analysis"],
        entries: [
            [0, 0, "Borrowing Costs Capitalization"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Average Accumulated Expenditures"],
            [3, 0, "Capitalization Rate %"],
            [4, 0, "Capitalization Months"],
            [5, 0, "Annual Avoidable Interest"],
            [5, 1, "=B3*B4"],
            [6, 0, "Capitalization Fraction"],
            [6, 1, "=B5/12"],
            [7, 0, "Capitalizable Borrowing Cost"],
            [7, 1, "=B6*B7"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "cost-plus-pricing-support",
        title: "Cost-Plus Pricing Sheet",
        description: "Support unit cost, target margin, suggested selling price, markup, and units needed for target income.",
        topic: "Operations & Supply Chain",
        sheetTitle: "Pricing",
        rowCount: 16,
        columnCount: 4,
        note: "Keep the cost base visible because pricing errors often begin with the wrong cost assumption rather than the wrong math.",
        tags: ["pricing", "cost plus", "operations"],
        relatedPaths: ["/operations/cost-plus-pricing", "/business/markup-margin"],
        entries: [
            [0, 0, "Cost-Plus Pricing Planner"],
            [1, 0, "Line Item"],
            [1, 1, "Input"],
            [2, 0, "Unit Cost"],
            [3, 0, "Target Margin %"],
            [4, 0, "Suggested Selling Price"],
            [5, 0, "Markup on Cost %"],
            [6, 0, "Target Monthly Income"],
            [7, 0, "Contribution per Unit"],
            [8, 0, "Units Needed"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "audit-assertion-evidence-support",
        title: "Audit Assertion and Evidence Sheet",
        description: "Lay out assertion focus, risk level, control reliance, evidence response, and working-paper wording support.",
        topic: "Audit & Assurance",
        sheetTitle: "Audit Assertions",
        rowCount: 18,
        columnCount: 5,
        note: "Use one row per major assertion when the case covers several balances or cycles.",
        tags: ["audit", "assertions", "evidence", "workpaper"],
        relatedPaths: ["/audit/assertion-evidence-planner", "/audit/audit-planning-workspace"],
        entries: [
            [0, 0, "Audit Assertion and Evidence Planner"],
            [1, 0, "Area / Cycle"],
            [1, 1, "Assertion"],
            [1, 2, "Risk"],
            [1, 3, "Control Reliance"],
            [1, 4, "Procedure / WP Note"],
            [2, 0, "Revenue and Collection"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "enterprise-systems-control-map",
        title: "Enterprise Systems Control Map",
        description: "Support ERP, SCM, CRM, or BI control mapping across access, change, interfaces, and documentation.",
        topic: "AIS & IT Controls",
        sheetTitle: "Systems Controls",
        rowCount: 18,
        columnCount: 5,
        note: "Use the blank rows for system modules, interfaces, or report outputs that need separate control notes.",
        tags: ["ais", "erp", "controls", "it audit"],
        relatedPaths: ["/ais/enterprise-systems-control-mapper", "/ais/it-control-matrix"],
        entries: [
            [0, 0, "Enterprise Systems Control Map"],
            [1, 0, "System / Module"],
            [1, 1, "Access"],
            [1, 2, "Change"],
            [1, 3, "Interface"],
            [1, 4, "Documentation / Note"],
            [2, 0, "ERP Core"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "ethics-decision-support",
        title: "Ethics Decision Support Sheet",
        description: "Capture issue area, stakeholder exposure, override risk, escalation path, and governance response in one review sheet.",
        topic: "Governance & Ethics",
        sheetTitle: "Ethics",
        rowCount: 16,
        columnCount: 5,
        note: "Use this as a reviewer worksheet when the case is less numeric and more about disciplined ethical response.",
        tags: ["ethics", "governance", "override", "risk"],
        relatedPaths: ["/governance/ethics-decision-workspace", "/governance/risk-control-matrix"],
        entries: [
            [0, 0, "Ethics Decision Support"],
            [1, 0, "Issue Area"],
            [1, 1, "Pressure"],
            [1, 2, "Stakeholder Impact"],
            [1, 3, "Override Risk"],
            [1, 4, "Escalation / Response"],
            [2, 0, "Reporting pressure"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "continuity-and-control-environment-support",
        title: "Continuity and Control Environment Sheet",
        description: "Capture recovery objectives, expected recovery, governance support, escalation readiness, and control gaps in one assignment-friendly template.",
        topic: "AIS & Governance",
        sheetTitle: "Continuity & Governance",
        rowCount: 20,
        columnCount: 6,
        note: "Use the top rows for continuity inputs and the lower rows for control-environment observations and action items.",
        tags: ["business continuity", "control environment", "governance", "ais"],
        relatedPaths: ["/ais/business-continuity-planner", "/governance/control-environment-review", "/governance/risk-control-matrix"],
        entries: [
            [0, 0, "Continuity and Control Environment"],
            [1, 0, "Continuity Input"],
            [1, 1, "Score / Hours"],
            [2, 0, "Backup and Recovery"],
            [3, 0, "Incident Response"],
            [4, 0, "Vendor Resilience"],
            [5, 0, "Communications Readiness"],
            [6, 0, "Target RTO (Hours)"],
            [7, 0, "Expected Recovery (Hours)"],
            [9, 0, "Governance Area"],
            [9, 1, "Observation"],
            [9, 2, "Risk"],
            [9, 3, "Response"],
            [10, 0, "Oversight / Tone at the Top"],
            [11, 0, "Escalation Path"],
            [12, 0, "Override Risk"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "balanced-scorecard-support",
        title: "Balanced Scorecard Support Sheet",
        description: "Map one strategic objective across financial, customer, process, and learning perspectives with measures and targets.",
        topic: "Strategic & Integrative",
        sheetTitle: "Scorecard",
        rowCount: 16,
        columnCount: 5,
        note: "Use one row per perspective measure when the case needs a fuller strategy map.",
        tags: ["balanced scorecard", "strategic", "performance"],
        relatedPaths: ["/strategic/balanced-scorecard-workspace", "/strategic/strategic-business-analysis"],
        entries: [
            [0, 0, "Balanced Scorecard Support"],
            [1, 0, "Perspective"],
            [1, 1, "Signal / Measure"],
            [1, 2, "Target"],
            [1, 3, "Owner"],
            [1, 4, "Follow-up"],
            [2, 0, "Financial"],
            [3, 0, "Customer"],
            [4, 0, "Internal Process"],
            [5, 0, "Learning and Growth"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "business-case-and-scorecard-support",
        title: "Business Case and Scorecard Sheet",
        description: "Support market attractiveness, execution readiness, control readiness, risk penalty, and recommended next-step metrics in one strategic worksheet.",
        topic: "Strategic & Integrative",
        sheetTitle: "Business Case",
        rowCount: 20,
        columnCount: 6,
        note: "Use this when a strategic recommendation must be justified before it becomes a balanced-scorecard or budgeting follow-up.",
        tags: ["business case", "strategic", "scorecard", "planning"],
        relatedPaths: ["/strategic/business-case-analysis", "/strategic/balanced-scorecard-workspace", "/strategic/strategic-business-analysis"],
        entries: [
            [0, 0, "Business Case and Scorecard Support"],
            [1, 0, "Strategic Factor"],
            [1, 1, "Score"],
            [1, 2, "Evidence"],
            [1, 3, "Risk / Gap"],
            [1, 4, "Owner"],
            [1, 5, "Next Step"],
            [2, 0, "Market Attractiveness"],
            [3, 0, "Cost Advantage"],
            [4, 0, "Control Readiness"],
            [5, 0, "Execution Capacity"],
            [6, 0, "Risk Penalty"],
            [8, 0, "Scorecard Perspective"],
            [9, 0, "Financial"],
            [10, 0, "Customer"],
            [11, 0, "Internal Process"],
            [12, 0, "Learning and Growth"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "statement-analysis-quality-support",
        title: "Statement Analysis Quality Sheet",
        description: "Support DuPont ROE, accrual ratio, and cash-conversion review from one statement-analysis workpaper.",
        topic: "Financial Statement Analysis",
        sheetTitle: "FSA Quality",
        rowCount: 18,
        columnCount: 5,
        note: "Use this with ratio-analysis, DuPont, and earnings-quality cases.",
        tags: ["dupont", "earnings quality", "ratio analysis"],
        relatedPaths: ["/accounting/dupont-analysis", "/accounting/earnings-quality-analysis", "/accounting/ratio-analysis-workspace"],
        entries: [
            [0, 0, "Statement Analysis Quality Support"],
            [1, 0, "Metric"],
            [1, 1, "Input / Formula"],
            [1, 2, "Result"],
            [1, 3, "Interpretation"],
            [2, 0, "Profit margin"],
            [3, 0, "Asset turnover"],
            [4, 0, "Equity multiplier"],
            [5, 0, "Accrual ratio"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "retail-pricing-and-rationing-support",
        title: "Retail Pricing and Capital Rationing Sheet",
        description: "Capture markup, markdown, maintained margin, and project-ranking decisions in one management-services sheet.",
        topic: "Cost & Managerial",
        sheetTitle: "Pricing & Rationing",
        rowCount: 20,
        columnCount: 6,
        note: "Use separate rows for retail products or competing capital projects.",
        tags: ["retail", "pricing", "capital rationing"],
        relatedPaths: ["/operations/retail-markup-markdown", "/finance/capital-rationing-prioritizer"],
        entries: [
            [0, 0, "Retail Pricing and Capital Rationing Support"],
            [1, 0, "Item / Project"],
            [1, 1, "Cost / Investment"],
            [1, 2, "Price / PV Inflows"],
            [1, 3, "Markdown / NPV"],
            [1, 4, "Margin / PI"],
            [1, 5, "Decision"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "provision-franchise-revenue-support",
        title: "Provision and Franchise Revenue Sheet",
        description: "Support FAR expected-value provisions and AFAR franchise-fee revenue recognition with visible assumptions.",
        topic: "FAR / AFAR",
        sheetTitle: "Provision & Franchise",
        rowCount: 20,
        columnCount: 5,
        note: "Use the top section for provision scenarios and the lower section for franchise obligation timing.",
        tags: ["provision", "franchise", "revenue"],
        relatedPaths: ["/far/provision-expected-value", "/afar/franchise-revenue-workspace"],
        entries: [
            [0, 0, "Provision and Franchise Revenue Support"],
            [1, 0, "Provision Scenario"],
            [1, 1, "Amount"],
            [1, 2, "Probability"],
            [1, 3, "Weighted Amount"],
            [7, 0, "Franchise Input"],
            [7, 1, "Amount / %"],
            [7, 2, "Result"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "confidence-interval-support",
        title: "Confidence Interval Support Sheet",
        description: "Document sample mean, standard error, margin of error, and interval interpretation for analytics cases.",
        topic: "Statistics & Analytics",
        sheetTitle: "Confidence Interval",
        rowCount: 16,
        columnCount: 5,
        note: "Use this for audit sampling, business analytics, or market-research estimates.",
        tags: ["statistics", "confidence interval", "sampling"],
        relatedPaths: ["/statistics/confidence-interval", "/statistics/standard-deviation"],
        entries: [
            [0, 0, "Confidence Interval Support"],
            [1, 0, "Sample Mean"],
            [2, 0, "Sample Standard Deviation"],
            [3, 0, "Sample Size"],
            [4, 0, "Confidence Level"],
            [5, 0, "Margin of Error"],
            [6, 0, "Lower Bound"],
            [7, 0, "Upper Bound"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "segmented-income-statement-support",
        title: "Segmented Income Statement Support Sheet",
        description: "Support contribution margin, segment margin, traceable fixed costs, and allocated common-cost review.",
        topic: "Cost & Managerial",
        sheetTitle: "Segment Margin",
        rowCount: 18,
        columnCount: 5,
        note: "Keep traceable fixed costs separate from allocated common fixed costs before making a responsibility-accounting conclusion.",
        tags: ["segment margin", "responsibility accounting", "performance"],
        relatedPaths: ["/business/segmented-income-statement", "/business/roi-ri-eva"],
        entries: [
            [0, 0, "Segmented Income Statement"],
            [1, 0, "Line Item"],
            [1, 1, "Amount"],
            [2, 0, "Sales"],
            [3, 0, "Variable Costs"],
            [4, 0, "Contribution Margin"],
            [4, 1, "=B3-B4"],
            [5, 0, "Traceable Fixed Costs"],
            [6, 0, "Segment Margin"],
            [6, 1, "=B5-B6"],
            [7, 0, "Allocated Common Fixed Costs"],
            [8, 0, "Income After Allocation"],
            [8, 1, "=B7-B8"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "audit-sampling-support",
        title: "Audit Sampling Support Sheet",
        description: "Document population value, tolerable misstatement, expected misstatement, confidence factor, sample size, and interval.",
        topic: "Audit & Assurance",
        sheetTitle: "Audit Sampling",
        rowCount: 18,
        columnCount: 5,
        note: "Use classroom confidence factors only when the instructor or problem provides them.",
        tags: ["audit sampling", "sample size", "evidence"],
        relatedPaths: ["/audit/audit-sampling-planner", "/audit/audit-planning-workspace"],
        entries: [
            [0, 0, "Audit Sampling Planner"],
            [1, 0, "Input"],
            [1, 1, "Amount / Factor"],
            [2, 0, "Population Book Value"],
            [3, 0, "Tolerable Misstatement"],
            [4, 0, "Expected Misstatement"],
            [5, 0, "Confidence Factor"],
            [6, 0, "Allowance for Sampling Risk"],
            [6, 1, "=B4-B5"],
            [7, 0, "Estimated Sample Size"],
            [8, 0, "Sampling Interval"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "pert-project-support",
        title: "PERT Project Estimate Support Sheet",
        description: "Capture optimistic, most-likely, pessimistic, expected time, standard deviation, and variance.",
        topic: "Operations & Supply Chain",
        sheetTitle: "PERT",
        rowCount: 16,
        columnCount: 5,
        note: "PERT is an estimate model, not a guarantee. Keep the activity assumption visible.",
        tags: ["pert", "project management", "operations"],
        relatedPaths: ["/operations/pert-project-estimate", "/operations/moving-average-forecast"],
        entries: [
            [0, 0, "PERT Project Estimate"],
            [1, 0, "Estimate"],
            [1, 1, "Time"],
            [2, 0, "Optimistic"],
            [3, 0, "Most Likely"],
            [4, 0, "Pessimistic"],
            [5, 0, "Expected Time"],
            [5, 1, "=(B3+4*B4+B5)/6"],
            [6, 0, "Standard Deviation"],
            [6, 1, "=(B5-B3)/6"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "liquidation-and-quasi-reorg-support",
        title: "Liquidation and Quasi-Reorganization Support Sheet",
        description: "Support corporate liquidation recovery and FAR deficit-cleanup assumptions in one distressed-entity workpaper.",
        topic: "AFAR / FAR",
        sheetTitle: "Recovery & Reorg",
        rowCount: 22,
        columnCount: 5,
        note: "Separate creditor priority and equity deficit relief before concluding on recovery or clean-surplus status.",
        tags: ["corporate liquidation", "quasi reorganization", "deficit"],
        relatedPaths: ["/afar/corporate-liquidation", "/far/quasi-reorganization"],
        entries: [
            [0, 0, "Liquidation and Quasi-Reorganization"],
            [1, 0, "Liquidation Input"],
            [1, 1, "Amount"],
            [2, 0, "Estimated Asset Realization"],
            [3, 0, "Liquidation Costs"],
            [4, 0, "Priority Liabilities"],
            [5, 0, "Unsecured Liabilities"],
            [6, 0, "Available to Unsecured"],
            [9, 0, "Quasi-Reorganization Input"],
            [10, 0, "Deficit"],
            [11, 0, "Share Premium Relief"],
            [12, 0, "Revaluation Surplus Relief"],
            [13, 0, "Capital Reduction"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "rfbt-ais-review-support",
        title: "RFBT and AIS Review Support Sheet",
        description: "Capture legal issue classification, remedy frame, access-control risks, and evidence notes in one reviewer sheet.",
        topic: "RFBT / AIS",
        sheetTitle: "Law & Access",
        rowCount: 18,
        columnCount: 5,
        note: "Use this for nonnumeric cases where issue framing and evidence quality matter more than formulas.",
        tags: ["rfbt", "ais", "access controls", "contracts"],
        relatedPaths: ["/rfbt/obligations-contracts-flow", "/ais/access-control-review"],
        entries: [
            [0, 0, "RFBT and AIS Review"],
            [1, 0, "Area"],
            [1, 1, "Issue"],
            [1, 2, "Risk / Effect"],
            [1, 3, "Evidence / Remedy"],
            [2, 0, "Obligations / Contracts"],
            [3, 0, "Access Controls"],
            [4, 0, "Segregation of Duties"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "defective-contracts-remedies-support",
        title: "Defective Contracts and Remedies Sheet",
        description: "Lay out defect type, enforceability, ratification risk, remedy path, and final legal consequence for RFBT coursework.",
        topic: "RFBT & Law",
        sheetTitle: "Defective Contracts",
        rowCount: 18,
        columnCount: 6,
        note: "Keep defect classification separate from remedy so the answer stays legally disciplined.",
        tags: ["defective contracts", "remedies", "rfbt", "annulment"],
        relatedPaths: ["/rfbt/defective-contracts-classifier", "/rfbt/obligations-contracts-flow", "/rfbt/business-law-review"],
        entries: [
            [0, 0, "Defective Contracts and Remedies"],
            [1, 0, "Issue"],
            [1, 1, "Facts"],
            [1, 2, "Classification"],
            [1, 3, "Enforceability"],
            [1, 4, "Remedy"],
            [1, 5, "Notes"],
            [2, 0, "Consent / Capacity"],
            [3, 0, "Writing / Authority"],
            [4, 0, "Illegality / Object"],
            [5, 0, "Ratification"],
            [6, 0, "Final Consequence"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "abc-and-quality-support",
        title: "ABC and Quality-Control Support Sheet",
        description: "Document activity cost pools, driver rates, assigned overhead, and three-sigma quality-control limits.",
        topic: "Cost & Operations",
        sheetTitle: "ABC & SQC",
        rowCount: 22,
        columnCount: 6,
        note: "Use this when product-costing and process-control evidence appear together in a management-services case.",
        tags: ["activity based costing", "abc", "quality control", "control chart"],
        relatedPaths: ["/business/activity-based-costing", "/operations/quality-control-chart"],
        entries: [
            [0, 0, "ABC and Quality-Control Support"],
            [1, 0, "ABC Input"],
            [1, 1, "Amount / Driver"],
            [2, 0, "Activity 1 Cost Pool"],
            [3, 0, "Activity 1 Driver"],
            [4, 0, "Activity 1 Rate"],
            [4, 1, "=B2/B3"],
            [5, 0, "Activity 2 Cost Pool"],
            [6, 0, "Activity 2 Driver"],
            [7, 0, "Activity 2 Rate"],
            [7, 1, "=B5/B6"],
            [10, 0, "Quality-Control Input"],
            [11, 0, "Process Mean"],
            [12, 0, "Standard Error"],
            [13, 0, "Lower Control Limit"],
            [14, 0, "Upper Control Limit"],
            [15, 0, "Out-of-Control Notes"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "financial-assets-and-investment-property",
        title: "Financial Assets and Investment Property Sheet",
        description: "Support amortized-cost financial assets, ECL allowance, and investment-property measurement comparisons.",
        topic: "FAR",
        sheetTitle: "Assets",
        rowCount: 22,
        columnCount: 6,
        note: "Keep classification assumptions visible before using the measurement outputs.",
        tags: ["financial assets", "investment property", "amortized cost", "fair value"],
        relatedPaths: ["/far/financial-asset-amortized-cost", "/far/investment-property-measurement"],
        entries: [
            [0, 0, "Financial Assets and Investment Property"],
            [1, 0, "Financial Asset Input"],
            [1, 1, "Amount"],
            [2, 0, "Opening Carrying Amount"],
            [3, 0, "Face Value"],
            [4, 0, "Cash Interest"],
            [5, 0, "Interest Revenue"],
            [6, 0, "Ending Gross Carrying Amount"],
            [7, 0, "ECL Allowance"],
            [8, 0, "Net Carrying Amount"],
            [11, 0, "Investment Property Input"],
            [12, 0, "Carrying Amount"],
            [13, 0, "Fair Value"],
            [14, 0, "Fair Value Gain / Loss"],
            [14, 1, "=B13-B12"],
            [15, 0, "Cost Model Depreciation"],
            [16, 0, "Cost Model Carrying Amount"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "joint-arrangement-support",
        title: "Joint Arrangement Support Sheet",
        description: "Capture participation percentage, share of statement amounts, and classification evidence for AFAR joint-arrangement cases.",
        topic: "AFAR",
        sheetTitle: "Joint Arrangement",
        rowCount: 18,
        columnCount: 6,
        note: "Percentage math supports the schedule, but rights and obligations still drive classification.",
        tags: ["joint arrangement", "joint operation", "joint venture", "afar"],
        relatedPaths: ["/afar/joint-arrangement-analyzer", "/afar/equity-method-investment"],
        entries: [
            [0, 0, "Joint Arrangement Support"],
            [1, 0, "Participation %"],
            [2, 0, "Arrangement Assets"],
            [3, 0, "Share of Assets"],
            [3, 1, "=B2*B1"],
            [4, 0, "Arrangement Liabilities"],
            [5, 0, "Share of Liabilities"],
            [5, 1, "=B4*B1"],
            [6, 0, "Arrangement Revenue"],
            [7, 0, "Arrangement Expenses"],
            [8, 0, "Share of Profit"],
            [8, 1, "=(B6-B7)*B1"],
            [11, 0, "Classification Evidence"],
            [12, 0, "Rights to Assets?"],
            [13, 0, "Obligations for Liabilities?"],
            [14, 0, "Equity Method Indicators?"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "assumptions-and-summary",
        title: "Assumptions and Summary Sheet",
        description: "Capture assumptions, key metrics, notes, and reviewer conclusions in one workpaper.",
        topic: "General",
        sheetTitle: "Assumptions & Summary",
        rowCount: 18,
        columnCount: 6,
        note: "Use this as a summary or cover sheet for multi-sheet workbooks and reporting-ready exports.",
        tags: ["summary", "assumptions", "reporting", "review"],
        relatedPaths: ["/workpapers", "/study-hub"],
        entries: [
            [0, 0, "Assumptions and Summary"],
            [1, 0, "Section"],
            [1, 1, "Details"],
            [2, 0, "Objective"],
            [3, 0, "Key assumptions"],
            [4, 0, "Data source"],
            [5, 0, "Result summary"],
            [6, 0, "Reviewer note"],
            [8, 0, "Next steps"],
        ],
    }),
    buildSingleSheetTemplate({
        templateId: "v13-revenue-tax-audit-cost-review",
        title: "V13 Academic Review Support Sheet",
        description: "Support revenue allocation, taxable-income bridge, audit evidence, and target-cost review in one integrated CPA-style sheet.",
        topic: "CPA Review Integration",
        sheetTitle: "Academic Review",
        rowCount: 28,
        columnCount: 7,
        note: "Use this template for mixed practical financial accounting cases where recognition, tax, audit evidence, and strategic cost management appear together.",
        tags: ["revenue", "taxable income", "audit evidence", "target costing", "cpa review"],
        relatedPaths: [
            "/far/revenue-allocation-workspace",
            "/tax/taxable-income-bridge",
            "/audit/evidence-program-builder",
            "/strategic/target-costing-workspace",
        ],
        entries: [
            [0, 0, "V13 Academic Review Support"],
            [1, 0, "Area"],
            [1, 1, "Input A"],
            [1, 2, "Input B"],
            [1, 3, "Input C"],
            [1, 4, "Result"],
            [1, 5, "Reviewer Note"],
            [2, 0, "Revenue Allocation"],
            [2, 1, "Transaction Price"],
            [2, 2, "SSP A"],
            [2, 3, "SSP B"],
            [2, 4, "Use revenue workspace"],
            [5, 0, "Taxable Income Bridge"],
            [5, 1, "Accounting Income"],
            [5, 2, "Permanent Items"],
            [5, 3, "Temporary Items"],
            [5, 4, "Use tax bridge"],
            [8, 0, "Audit Evidence"],
            [8, 1, "Assertion Risk"],
            [8, 2, "Reliability"],
            [8, 3, "Relevance"],
            [8, 4, "Use evidence builder"],
            [11, 0, "Target Costing"],
            [11, 1, "Target Price"],
            [11, 2, "Target Margin"],
            [11, 3, "Estimated Cost"],
            [11, 4, "Use target cost workspace"],
            [15, 0, "Integrated conclusion"],
        ],
    }),
];

export function getWorkpaperTemplate(templateId: string) {
    return WORKPAPER_TEMPLATES.find((template) => template.id === templateId) ?? null;
}
