function makeTopic(seed) {
    return {
        id: seed.id,
        title: seed.title,
        shortTitle: seed.shortTitle,
        category: seed.category,
        summary: seed.summary,
        intro: seed.intro,
        whyItMatters: [
            `It helps students explain ${seed.focus} as a structured process instead of a memorized fragment.`,
            "It keeps the lesson tied to board-style interpretation and not only textbook wording.",
            "It improves route selection inside AccCalc because the topic signals are clearer.",
        ],
        classContexts: [
            `${seed.shortTitle} reviewer sessions`,
            "Board-review style mixed cases",
            "Short-answer and concept-explanation drills",
        ],
        whenToUse: [
            `Use this topic when the case is primarily about ${seed.focus}.`,
            "Use it before a workspace when you need the concept map first.",
            "Use it after a mistake when wrong classification was the real problem.",
        ],
        formulaOverview: [
            {
                label: "Review structure",
                expression: `${seed.shortTitle}: classify the issue -> apply the core rule or framework -> interpret the consequence`,
                explanation: "This lesson is structured as a reviewer path so the main issue becomes clear before detailed solving begins.",
            },
        ],
        variableDefinitions: [
            { symbol: "Primary issue", meaning: "The main idea or question the case is really asking" },
            { symbol: "Supporting issue", meaning: "A second idea that affects interpretation or route choice" },
        ],
        procedure: [
            "Identify the primary issue before choosing a calculator or answer path.",
            "Separate the conceptual rule from the supporting facts.",
            "State the likely effect, risk, or conclusion clearly.",
            "Link the answer to the next AccCalc tool or lesson when needed.",
        ],
        workedExample: {
            title: `${seed.shortTitle} worked example`,
            scenario: seed.workedScenario,
            steps: [
                "Classify the issue first.",
                "Apply the core framework or rule to the facts.",
                "Explain the consequence in plain language.",
                "Choose the best next calculator, lesson, or practice route.",
            ],
            result: seed.workedResult,
            interpretation: "The value of the lesson is the structure it gives the student before detailed solving begins.",
        },
        checkpointExample: {
            title: `${seed.shortTitle} checkpoint`,
            scenario: seed.checkpointScenario,
            steps: [
                "Pause the first instinctive route choice.",
                "Re-check the actual issue being asked.",
                "Redirect the answer using the correct framework.",
            ],
            result: seed.checkpointResult,
            interpretation: "The checkpoint exists to catch wrong routing or shallow interpretation before it spreads through the full answer.",
        },
        interpretation: [
            `A strong ${seed.shortTitle.toLowerCase()} answer starts with classification before detail.`,
            "A correct number can still sit inside a weak answer if the issue was framed badly.",
            "Use follow-up tools only after the lesson structure is clear.",
        ],
        commonMistakes: [
            "Jumping into a familiar formula or rule before classifying the case.",
            "Listing facts without naming the issue clearly.",
            "Ignoring the final consequence or interpretation.",
        ],
        examTraps: [
            "The first familiar keyword in a case may not point to the main issue.",
            "A question may mix two subjects, but only one is primary for the first route choice.",
            "Students often stop at computation and forget the broader conclusion.",
        ],
        selfCheck: [
            "What is the primary issue here?",
            "What supporting issue still affects the final answer?",
            "Which AccCalc route best fits the next step after this lesson?",
        ],
        practiceCues: [
            "Explain the issue in one sentence before solving.",
            "State one common wrong route for this topic.",
            "Describe the final consequence that should appear in the answer.",
        ],
        deepDiveSections: seed.deepDiveSections ??
            [
                {
                    id: `${seed.id}-framework`,
                    title: "Framework distinction",
                    summary: "Open this when similar labels or nearby topics are starting to blur together.",
                    points: [
                        `Keep ${seed.focus} separate from nearby but different classification issues.`,
                        "State the controlling rule or framework before moving into numbers or consequences.",
                        "Use the route that solves the primary issue first, then deal with supporting issues.",
                    ],
                    tone: "info",
                },
                {
                    id: `${seed.id}-review`,
                    title: "Reviewer emphasis",
                    summary: "Use this for board-review or short-answer framing.",
                    points: [
                        "Name the issue clearly before discussing detail.",
                        "Connect the rule to the fact pattern instead of listing memorized fragments.",
                        "End with the actual effect, conclusion, or recommended next step.",
                    ],
                    tone: "default",
                },
            ],
        nextStepPrompts: seed.nextStepPrompts ??
            [
                "Open the most closely related calculator only after you can explain why it fits the issue.",
                "Move into quiz mode when you can classify the case without relying on the worked example.",
                "Use an integrative or reviewer topic next if the fact pattern is mixed rather than single-topic.",
            ],
        keywords: seed.keywords,
        scanSignals: seed.scanSignals,
        relatedCalculatorPaths: seed.relatedCalculatorPaths,
        relatedTopicIds: seed.relatedTopicIds,
        quiz: {
            title: `${seed.shortTitle} Check`,
            intro: `Use this short set to verify whether you can classify and interpret ${seed.shortTitle.toLowerCase()} cases accurately.`,
            questions: [
                {
                    id: `${seed.id}-q1`,
                    kind: "multiple-choice",
                    prompt: "What should usually happen before opening the most detailed route?",
                    choices: [
                        "Classify the primary issue",
                        "Skip directly to the longest calculation",
                        "Ignore the supporting facts",
                        "Answer without interpretation",
                    ],
                    answerIndex: 0,
                    explanation: "The best first step is usually proper classification of the case, not premature solving.",
                },
                {
                    id: `${seed.id}-q2`,
                    kind: "true-false",
                    prompt: "A familiar keyword always tells you the correct route immediately.",
                    answer: false,
                    explanation: "Mixed cases often contain misleading familiar words that are not the real primary issue.",
                },
                {
                    id: `${seed.id}-q3`,
                    kind: "short-answer",
                    prompt: "Why is issue classification important before detailed solving?",
                    acceptedAnswers: [
                        "because it helps choose the right route",
                        "because wrong routing leads to weak answers",
                        "because it keeps the interpretation accurate",
                    ],
                    explanation: "Correct classification protects both the computation route and the final interpretation.",
                },
            ],
        },
    };
}
export const STUDY_HUB_CURRICULUM_TOPICS = [
    makeTopic({
        id: "afar-business-combinations-and-consolidation",
        title: "AFAR: Business Combinations and Consolidation",
        shortTitle: "AFAR Combination",
        category: "AFAR / Consolidation",
        summary: "Review goodwill, NCI measurement, and consolidation purpose before moving into more detailed AFAR cases.",
        intro: "AFAR cases are easier when acquisition-date logic and consolidation purpose are understood before later-period adjustments are attempted.",
        focus: "goodwill, NCI, and consolidation-at-acquisition logic",
        workedScenario: "A parent acquires a controlling interest, the case gives fair values, and the student must explain goodwill and the role of consolidation entries.",
        workedResult: "The strongest answer explains both the acquisition-date measurement and why the group is presented as one reporting entity.",
        checkpointScenario: "A student leaves the parent's investment account untouched in the consolidated statement.",
        checkpointResult: "Consolidation answers are stronger when the purpose of elimination is clear and not treated as a mechanical rule only.",
        keywords: ["afar", "business combination", "goodwill", "nci", "consolidation"],
        scanSignals: ["consideration transferred", "goodwill", "non controlling interest", "consolidated"],
        relatedCalculatorPaths: ["/afar/business-combination-analysis"],
        relatedTopicIds: ["integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "audit-planning-evidence-and-reporting",
        title: "Audit Planning, Evidence, and Reporting Flow",
        shortTitle: "Audit Flow",
        category: "Audit & Assurance",
        summary: "Study materiality, audit risk, evidence, completion procedures, and report formulation as one assurance workflow.",
        intro: "Audit topics become easier when they are treated as one flow from planning through evidence and finally reporting.",
        focus: "materiality, risk assessment, evidence, and reporting consequence",
        workedScenario: "A case gives a materiality benchmark, high revenue risk, weak controls, and then asks what procedures and report implications follow.",
        workedResult: "The answer should connect planning choices to evidence response and then to the final reporting implication.",
        checkpointScenario: "A student lists many audit procedures but cannot explain why they fit the assessed risk.",
        checkpointResult: "Audit procedures are stronger when they are linked to assertions, risk, and final reporting effect.",
        keywords: ["audit planning", "materiality", "audit risk", "audit evidence", "audit report"],
        scanSignals: ["inherent risk", "control risk", "detection risk", "audit report", "audit evidence"],
        relatedCalculatorPaths: ["/audit/audit-planning-workspace", "/ais/it-control-matrix"],
        relatedTopicIds: ["ais-it-governance-and-controls", "governance-risk-ethics-and-internal-control"],
    }),
    makeTopic({
        id: "tax-book-tax-vat-and-compliance",
        title: "Tax Logic: Income, VAT, and Book-Tax Differences",
        shortTitle: "Tax Logic",
        category: "Taxation",
        summary: "Review taxable-income logic, VAT structure, and book-tax differences without mixing legal and accounting labels.",
        intro: "Tax questions often look numeric, but the real challenge is keeping the labels, legal basis, and accounting effects separate.",
        focus: "taxable-income bridging, VAT structure, and careful compliance framing",
        workedScenario: "A case gives accounting income, permanent and temporary differences, and asks for current tax plus a deferred effect.",
        workedResult: "The strongest answer labels the type of difference clearly before interpreting the tax effect.",
        checkpointScenario: "A student treats tax evasion as a stronger form of normal tax planning.",
        checkpointResult: "Tax analysis must keep legal and ethical compliance distinctions explicit, not implied.",
        keywords: ["taxation", "taxable income", "book tax differences", "vat", "deferred tax"],
        scanSignals: ["taxable income", "temporary difference", "permanent difference", "vat payable"],
        relatedCalculatorPaths: ["/tax/book-tax-difference-workspace", "/accounting/philippine-vat"],
        relatedTopicIds: ["governance-risk-ethics-and-internal-control", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "rfbt-obligations-contracts-and-corporation-law",
        title: "RFBT: Obligations, Contracts, and Corporation Law",
        shortTitle: "RFBT Core",
        category: "RFBT / Business Law",
        summary: "Use a structured issue-spotting map for obligations, contracts, remedies, and corporation-law review questions.",
        intro: "RFBT questions become much easier when the answer is organized around issue, rule, application, and consequence.",
        focus: "legal issue spotting, rule application, and consequence reading",
        workedScenario: "A case asks whether a contract is enforceable, who had authority to act, and what remedy follows a failure to perform.",
        workedResult: "The answer becomes stronger when the issue is named clearly before the rule and remedy are discussed.",
        checkpointScenario: "A student retells the facts at length but never states the controlling issue or legal effect.",
        checkpointResult: "A business-law answer is weak if it never moves from fact summary into consequence analysis.",
        keywords: ["rfbt", "contracts", "obligations", "corporation law", "remedies"],
        scanSignals: ["remedy", "obligation", "contract", "board", "corporation"],
        relatedCalculatorPaths: ["/rfbt/business-law-review"],
        relatedTopicIds: ["governance-risk-ethics-and-internal-control", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "ais-it-governance-and-controls",
        title: "AIS, IT Governance, and Control Environment",
        shortTitle: "AIS and IT Controls",
        category: "AIS / IT Controls",
        summary: "Review IT governance, general controls, application controls, documentation, and IT-audit relevance in one AIS study path.",
        intro: "AIS topics become clearer when governance, general controls, and application controls are kept distinct and then tied back to reporting reliability.",
        focus: "IT governance, control layers, documentation, and IT-audit consequence",
        workedScenario: "A case describes weak access review, undocumented program changes, and incomplete backup testing in a financial system environment.",
        workedResult: "The strongest answer separates the control layers, explains the weakness, and links it to reliability and audit response.",
        checkpointScenario: "A student describes every system weakness as an application-control issue.",
        checkpointResult: "Correct control classification improves both AIS understanding and IT-audit interpretation.",
        keywords: ["ais", "it governance", "it controls", "application controls", "it audit"],
        scanSignals: ["access controls", "change management", "backup", "application controls", "itgc"],
        relatedCalculatorPaths: ["/ais/it-control-matrix", "/audit/audit-planning-workspace"],
        relatedTopicIds: ["audit-planning-evidence-and-reporting", "governance-risk-ethics-and-internal-control"],
    }),
    makeTopic({
        id: "operations-forecasting-inventory-and-quality",
        title: "Operations: Forecasting, Inventory, and Quality",
        shortTitle: "Operations Review",
        category: "Operations / Supply Chain",
        summary: "Connect forecasting, EOQ, reorder points, capacity, and quality review into one operations-management study path.",
        intro: "Operations tools are most useful when students see how demand planning, replenishment, capacity, and quality decisions affect one another.",
        focus: "forecasting, replenishment, capacity, and quality tradeoffs",
        workedScenario: "A manufacturer needs an inventory policy while supplier lead time, plant capacity, and service expectations all matter at once.",
        workedResult: "The best answer combines the computed policy with a practical explanation of operations tradeoffs.",
        checkpointScenario: "A student treats the cheapest inventory policy as automatically the best operational answer.",
        checkpointResult: "Operations answers improve when quality, service, and capacity are evaluated alongside cost.",
        keywords: ["operations management", "eoq", "reorder point", "quality", "forecasting"],
        scanSignals: ["economic order quantity", "reorder point", "lead time", "safety stock", "quality"],
        relatedCalculatorPaths: [
            "/operations/eoq-and-reorder-point",
            "/business/capacity-utilization",
            "/accounting/inventory-control-workspace",
        ],
        relatedTopicIds: ["operating-capacity-and-planning-review", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "governance-risk-ethics-and-internal-control",
        title: "Governance, Ethics, Risk, and Internal Control",
        shortTitle: "Governance and Risk",
        category: "Governance / Ethics / Risk",
        summary: "Study ethics, governance structure, risk assessment, and internal-control design and evaluation as one professional-judgment pathway.",
        intro: "Governance and internal-control topics become more useful when risk, ethics, and oversight are treated as connected ideas instead of isolated definitions.",
        focus: "risk identification, control response, ethical pressure, and governance consequence",
        workedScenario: "A case describes aggressive targets, weak approvals, and poor monitoring of exceptions in a sensitive reporting area.",
        workedResult: "The strongest answer identifies the risk, explains the control weakness, and states the residual governance exposure clearly.",
        checkpointScenario: "A student says trusted managers make documentation and formal controls unnecessary.",
        checkpointResult: "Good governance does not rely on trust alone; it still requires structure, evidence, and accountability.",
        keywords: ["governance", "ethics", "risk management", "internal control", "residual risk"],
        scanSignals: ["internal control", "ethics", "risk assessment", "control weakness", "residual risk"],
        relatedCalculatorPaths: ["/governance/risk-control-matrix", "/audit/audit-planning-workspace"],
        relatedTopicIds: ["audit-planning-evidence-and-reporting", "ais-it-governance-and-controls"],
    }),
    makeTopic({
        id: "far-leases-share-based-payments-and-equity-special-topics",
        title: "FAR: Leases, Share-Based Payments, and Equity Special Topics",
        shortTitle: "FAR Equity Depth",
        category: "Financial Accounting",
        summary: "Review lease measurement, share-based payment recognition, treasury-share and retained-earnings effects, and broader equity special topics in one FAR lesson.",
        intro: "These FAR areas are easy to misread because they combine measurement, classification, and statement presentation. The topic works best when the issue is identified before the numbers are pushed through a worksheet.",
        focus: "lease measurement, equity-settled compensation, and special equity presentation",
        workedScenario: "A case gives lease payments, a vesting schedule for options, and a separate equity adjustment issue in retained earnings.",
        workedResult: "The strongest answer keeps lease liability logic, compensation-cost timing, and equity-presentation consequences separate instead of collapsing them into one entry.",
        checkpointScenario: "A student records a lease from undiscounted payments and treats share-based compensation as an immediate full expense with no service-period logic.",
        checkpointResult: "FAR depth answers are stronger when present-value measurement, vesting period, and equity labels are handled deliberately.",
        keywords: ["leases", "share-based payments", "treasury shares", "retained earnings", "equity"],
        scanSignals: ["right of use", "lease liability", "stock options", "retained earnings", "treasury shares"],
        relatedCalculatorPaths: ["/far/lease-measurement-workspace", "/far/share-based-payment-workspace"],
        relatedTopicIds: ["far-cash-flow-and-statement-classification", "integrative-review-and-case-mapping"],
        deepDiveSections: [
            {
                id: "far-equity-lease-distinction",
                title: "Lease versus equity presentation",
                summary: "Use this when measurement and presentation issues appear in the same fact pattern.",
                points: [
                    "Lease questions usually start with present-value measurement and later expense pattern consequences.",
                    "Share-based payment questions usually start with grant-date fair value, expected vesting, and service-period recognition.",
                    "Equity special topics become stronger when retained earnings, treasury shares, and share capital labels stay distinct.",
                ],
                tone: "info",
            },
            {
                id: "far-quasi-reorg",
                title: "Quasi-reorganization and retained-earnings caution",
                summary: "Open this for special retained-earnings and capital-structure review.",
                points: [
                    "Quasi-reorganization topics are not routine retained-earnings entries; they are special capital-structure and deficit-cleanup cases.",
                    "Always state the effect on capital accounts and presentation rather than listing adjustments only.",
                    "If the case mixes equity cleanup with valuation, identify which issue is primary first.",
                ],
                tone: "warning",
            },
        ],
        nextStepPrompts: [
            "Open the lease workspace next when the case gives payment timing, discounting, or right-of-use measurement facts.",
            "Open the share-based payment workspace next when the case is mainly about vesting, forfeiture, or cumulative compensation cost.",
            "Move into integrative review when the same fact pattern also involves cash-flow or disclosure consequences.",
        ],
    }),
    makeTopic({
        id: "far-cash-flow-and-statement-classification",
        title: "FAR: Cash Flow Statement and Statement Classification Support",
        shortTitle: "Cash Flow Support",
        category: "Financial Accounting",
        summary: "Study indirect-method cash-flow logic, operating-investing-financing classification, and statement-building judgment without losing the presentation meaning.",
        intro: "Cash-flow questions often look like arithmetic, but the real difficulty is classification. Students get stronger faster when they learn why the line belongs in operating, investing, or financing activities.",
        focus: "indirect-method cash-flow building and statement classification",
        workedScenario: "A case gives net income, noncash charges, working-capital changes, capital expenditures, debt flows, and dividends.",
        workedResult: "The strongest answer explains the operating adjustments first, then keeps investing and financing lines separate instead of netting unrelated items together.",
        checkpointScenario: "A student leaves gains on asset sale inside operating cash flow and classifies debt proceeds as operating activity.",
        checkpointResult: "Classification is the real issue in many cash-flow cases, so the answer must explain the section logic clearly.",
        keywords: ["statement of cash flows", "indirect method", "cash flow classification", "operating financing investing"],
        scanSignals: ["cash flows from operating", "indirect method", "investing activities", "financing activities"],
        relatedCalculatorPaths: ["/far/cash-flow-statement-builder"],
        relatedTopicIds: ["far-leases-share-based-payments-and-equity-special-topics", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "afar-foreign-currency-branch-and-home-office",
        title: "AFAR: Foreign Currency, Branch, and Home Office Support",
        shortTitle: "AFAR FX and Branch",
        category: "AFAR / Consolidation",
        summary: "Review foreign-currency transactions, settlement and translation effects, and branch-home-office accounting structure in one AFAR lesson.",
        intro: "AFAR foreign-currency and branch cases become easier when students separate transaction-date recognition, end-of-period translation, and interoffice-account logic.",
        focus: "foreign-currency measurement and branch-home-office structure",
        workedScenario: "A branch records transactions in a different currency and the case asks for home-office and reporting-currency consequences.",
        workedResult: "A strong answer separates the exchange-rate issue from the interoffice-account issue before solving.",
        checkpointScenario: "A student treats every foreign-currency effect as a branch-adjustment issue.",
        checkpointResult: "AFAR answers improve when foreign-currency effects and interoffice structure are not mixed carelessly.",
        keywords: ["foreign currency", "branch accounting", "home office", "translation"],
        scanSignals: ["exchange rate", "home office", "branch current", "closing rate"],
        relatedCalculatorPaths: ["/afar/foreign-currency-translation"],
        relatedTopicIds: ["afar-business-combinations-and-consolidation", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "afar-franchise-consignment-construction-and-subscriptions",
        title: "AFAR: Franchise, Consignment, Construction, and Subscription Cases",
        shortTitle: "AFAR Special Revenue",
        category: "AFAR / Consolidation",
        summary: "Review special AFAR revenue and reporting topics such as franchise, consignment, long-term construction, subscriptions, warranties, and service contracts.",
        intro: "These special topics look different on the surface, but many of them test the same core idea: identify what has really been earned, recognized, or retained by the reporting entity.",
        focus: "special-revenue recognition and special reporting structure",
        workedScenario: "A case mixes long-term construction progress, a consignment relationship, and later warranty exposure.",
        workedResult: "The best answer identifies who bears the reporting consequence before discussing revenue, cost, or liability timing.",
        checkpointScenario: "A student records consignment goods as ordinary sales inventory and treats subscription receipts as fully earned immediately.",
        checkpointResult: "Special AFAR cases reward careful classification of control, earning process, and later obligations.",
        keywords: ["franchise", "consignment", "construction contract", "subscriptions", "warranty", "service contract"],
        scanSignals: ["consignment", "franchise fee", "percentage of completion", "subscriptions", "warranty"],
        relatedCalculatorPaths: ["/afar/construction-revenue-workspace"],
        relatedTopicIds: ["afar-foreign-currency-branch-and-home-office", "tax-book-tax-vat-and-compliance"],
    }),
    makeTopic({
        id: "tax-withholding-transfer-and-incentive-regimes",
        title: "Tax: Withholding, Transfer Taxes, Treaty Handling, and Incentive Regimes",
        shortTitle: "Tax Special Topics",
        category: "Taxation",
        summary: "Review withholding taxes, documentary stamp tax, excise, estate and donor's tax, local taxation, treaty handling, and incentive-regime logic carefully and professionally.",
        intro: "These tax topics are classification-heavy. The issue is often not a formula first, but the legal base, triggering event, jurisdiction, or incentive status behind the case.",
        focus: "special-tax classification, compliance framing, and legal-vs-accounting distinction",
        workedScenario: "A case asks whether a transaction falls under withholding, local taxation overlap, or an incentive-regime exception.",
        workedResult: "The strongest answer starts with tax type, legal basis, and compliance consequence before moving into any tax base or rate discussion.",
        checkpointScenario: "A student treats all tax reduction planning as automatically improper or, in the other direction, treats any aggressive arrangement as valid planning.",
        checkpointResult: "Tax analysis becomes more reliable when legal compliance, ethical planning, and evasion are kept distinct.",
        keywords: ["withholding tax", "dst", "estate tax", "donor's tax", "tax treaty", "peza", "boi"],
        scanSignals: ["withholding", "documentary stamp", "estate tax", "donor's tax", "tax treaty", "peza"],
        relatedCalculatorPaths: ["/tax/tax-compliance-review", "/tax/book-tax-difference-workspace"],
        relatedTopicIds: ["tax-book-tax-vat-and-compliance", "governance-risk-ethics-and-internal-control"],
    }),
    makeTopic({
        id: "audit-transaction-cycles-and-cis",
        title: "Audit: Transaction Cycles, CIS Environment, and CAATs",
        shortTitle: "Audit Cycles and CIS",
        category: "Audit & Assurance",
        summary: "Study revenue, expenditure, conversion, and financing cycles together with CIS environments, general versus application controls, and CAATs support.",
        intro: "Audit cycle cases become clearer when assertions, controls, IT environment, and procedure choice are treated as one chain rather than separate memorized lists.",
        focus: "cycle assertions, IT-control context, and audit response selection",
        workedScenario: "A revenue-cycle case includes weak application controls and asks for likely audit procedures and evidence consequences.",
        workedResult: "The strongest answer identifies the cycle assertion first, then connects the CIS weakness to the audit response.",
        checkpointScenario: "A student lists CAATs as if they automatically solve weak controls without explaining the audit objective.",
        checkpointResult: "Audit technology tools only strengthen the answer when they are matched to the assertion and risk being tested.",
        keywords: ["audit cycle", "revenue cycle", "cais", "caats", "application controls"],
        scanSignals: ["revenue cycle", "expenditure cycle", "application controls", "caats", "cis environment"],
        relatedCalculatorPaths: ["/audit/audit-cycle-reviewer", "/ais/it-control-matrix"],
        relatedTopicIds: ["audit-planning-evidence-and-reporting", "ais-it-governance-and-controls"],
    }),
    makeTopic({
        id: "audit-completion-modified-reports-and-kams",
        title: "Audit: Completion Procedures, Modified Reports, and Key Audit Matters",
        shortTitle: "Audit Completion",
        category: "Audit & Assurance",
        summary: "Review completion procedures, subsequent events, going concern, representation letters, report formulation, modified opinions, and key audit matters as one closing workflow.",
        intro: "The closing stage of an audit is easier when students stop seeing each issue as isolated. Going concern, subsequent events, and reporting are part of the same final judgment flow.",
        focus: "completion judgment, reporting consequence, and opinion formulation",
        workedScenario: "A case presents late events, going-concern pressure, and a possible scope limitation near report date.",
        workedResult: "A strong answer distinguishes the nature of the issue first, then explains the reporting consequence and whether KAM or modification is involved.",
        checkpointScenario: "A student treats every serious matter as a modified opinion and every KAM as if it changes the opinion.",
        checkpointResult: "Completion answers improve when reporting categories are separated carefully before the final conclusion is stated.",
        keywords: ["modified report", "going concern", "subsequent events", "key audit matters"],
        scanSignals: ["going concern", "subsequent event", "modified opinion", "key audit matter"],
        relatedCalculatorPaths: ["/audit/audit-completion-and-opinion", "/audit/audit-planning-workspace"],
        relatedTopicIds: ["audit-transaction-cycles-and-cis", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "rfbt-sales-credit-security-and-securities",
        title: "RFBT: Sales, Credit Transactions, Security, and Securities Regulation",
        shortTitle: "RFBT Commercial Law",
        category: "RFBT / Business Law",
        summary: "Review sales and credit transactions, contracts of security, securities law, insider trading, fraud, and market manipulation in one business-law lesson.",
        intro: "Commercial-law questions become stronger when the transaction type is classified first and the legal consequence is stated clearly afterward.",
        focus: "commercial-transaction issue spotting and regulatory consequence",
        workedScenario: "A case asks whether a transaction created enforceable rights, whether security exists, and whether a market-conduct rule was breached.",
        workedResult: "The strongest answer names the transaction or rule first, then explains the consequence instead of retelling the facts.",
        checkpointScenario: "A student describes what happened but never states the controlling commercial-law issue.",
        checkpointResult: "RFBT answers need issue, rule, application, and consequence structure to stay convincing.",
        keywords: ["sales law", "credit transactions", "security", "insider trading", "securities regulation"],
        scanSignals: ["security agreement", "insider trading", "fraud", "manipulation", "sales transaction"],
        relatedCalculatorPaths: ["/rfbt/commercial-transactions-reviewer", "/rfbt/business-law-review"],
        relatedTopicIds: ["rfbt-obligations-contracts-and-corporation-law", "governance-risk-ethics-and-internal-control"],
    }),
    makeTopic({
        id: "ais-bcp-erp-and-service-management",
        title: "AIS: Continuity, ERP, Service Management, and Disaster Recovery",
        shortTitle: "AIS Continuity",
        category: "AIS / IT Controls",
        summary: "Study business continuity, disaster recovery, ERP, supply chain modules, CRM, incident management, and capacity planning with an AIS and control perspective.",
        intro: "AIS questions are easier when the student separates platform role, continuity responsibility, and control consequence instead of treating the system as one vague black box.",
        focus: "system role, continuity planning, and control consequence",
        workedScenario: "An ERP-driven environment has weak backup testing, high system dependence, and unclear incident management escalation.",
        workedResult: "The best answer identifies the operational role of the system first, then explains why continuity and control issues matter for reporting and audit.",
        checkpointScenario: "A student describes disaster recovery as if it already covers full business continuity planning.",
        checkpointResult: "AIS answers improve when continuity, recovery, governance, and daily service management are separated clearly.",
        keywords: ["business continuity", "disaster recovery", "erp", "crm", "incident management"],
        scanSignals: ["disaster recovery", "erp", "incident management", "capacity planning", "continuity"],
        relatedCalculatorPaths: ["/ais/ais-lifecycle-and-recovery", "/ais/it-control-matrix"],
        relatedTopicIds: ["ais-it-governance-and-controls", "audit-transaction-cycles-and-cis"],
    }),
    makeTopic({
        id: "strategic-business-analysis-and-cost-management",
        title: "Strategic Business Analysis, Strategic Cost Management, and Integrative Framing",
        shortTitle: "Strategic Analysis",
        category: "Strategic / Integrative",
        summary: "Use a strategic lens for industry and competition analysis, strategic cost management, consultancy-style advice, and research-method framing for integrative accounting cases.",
        intro: "Integrative cases become more useful when students can explain the business problem first, then show how accounting, operations, governance, and tax issues fit the strategic picture.",
        focus: "strategic framing, cost-management diagnosis, and integrative decision support",
        workedScenario: "A company faces margin pressure, operational bottlenecks, and control concerns while the case asks for an advisory recommendation.",
        workedResult: "The strongest answer identifies the strategic problem, links it to the cost and control drivers, and then recommends a defensible next step.",
        checkpointScenario: "A student gives a ratio-heavy answer but never states the competitive or operating issue behind the numbers.",
        checkpointResult: "Strategic topics get stronger when the numeric evidence is turned into a business conclusion and recommendation.",
        keywords: ["strategic business analysis", "strategic cost management", "consultancy", "industry analysis"],
        scanSignals: ["industry analysis", "competitive pressure", "strategic cost management", "consultancy"],
        relatedCalculatorPaths: ["/strategic/strategic-business-analysis", "/strategic/integrative-case-mapper", "/business/roi-ri-eva"],
        relatedTopicIds: ["integrative-review-and-case-mapping", "operations-forecasting-inventory-and-quality"],
    }),
    makeTopic({
        id: "integrative-review-and-case-mapping",
        title: "Integrative Review and Case Mapping",
        shortTitle: "Integrative Review",
        category: "Strategic / Integrative",
        summary: "Use a capstone-style study topic to map mixed cases across FAR, AFAR, managerial, audit, tax, law, AIS, and governance before solving.",
        intro: "Capstone and board-review cases are often mixed-topic by design. Strong performance depends on classifying the case correctly before solving.",
        focus: "primary-issue mapping, secondary-issue awareness, and route selection",
        workedScenario: "A case mixes inventory measurement, control weakness, and a possible reporting consequence in one fact pattern.",
        workedResult: "The best route is the one that solves the primary issue first while keeping the secondary issue visible for the final interpretation.",
        checkpointScenario: "A student chooses a tax workspace because of one familiar word even though the main issue is inventory measurement.",
        checkpointResult: "Wrong initial routing can produce neat arithmetic inside the wrong overall answer.",
        keywords: ["integrative review", "board review", "case mapping", "capstone"],
        scanSignals: ["mixed topic", "board review", "integrated case", "capstone"],
        relatedCalculatorPaths: ["/strategic/integrative-case-mapper", "/smart/solver", "/scan-check"],
        relatedTopicIds: [
            "audit-planning-evidence-and-reporting",
            "tax-book-tax-vat-and-compliance",
            "operations-forecasting-inventory-and-quality",
        ],
    }),
    makeTopic({
        id: "far-framework-accounting-cycle-and-profession",
        title: "FAR Foundations: Conceptual Framework, Accounting Cycle, and the Profession",
        shortTitle: "FAR Foundations",
        category: "Financial Accounting",
        summary: "Review the conceptual framework, the accounting cycle, and the Philippine accountancy-profession setting before moving into specialized FAR calculations.",
        intro: "Many FAR mistakes start before the numbers. Students often confuse recognition, measurement, presentation, and the accounting-cycle sequence because the framework was never made explicit.",
        focus: "recognition logic, accounting-cycle order, and professional reporting context",
        workedScenario: "A case asks whether an item should be recognized now, adjusted later, or only disclosed in the notes, while the student also needs to identify the step in the accounting cycle.",
        workedResult: "The strongest answer explains the framework issue first, then places the item in the correct cycle step and reporting consequence.",
        checkpointScenario: "A student treats every uncertainty like an automatic journal entry even when note disclosure or later adjustment is more appropriate.",
        checkpointResult: "Framework-first thinking improves both route choice and final FAR explanations.",
        keywords: ["conceptual framework", "accounting cycle", "philippine accountancy profession", "recognition"],
        scanSignals: ["recognition", "measurement", "disclosure", "adjusting entry", "closing entry"],
        relatedCalculatorPaths: ["/accounting/adjusting-entries-workspace", "/accounting/trial-balance-checker"],
        relatedTopicIds: ["far-equity-dividends-and-retained-earnings"],
    }),
    makeTopic({
        id: "far-equity-dividends-and-retained-earnings",
        title: "FAR: Equity Changes, Dividends, and Retained Earnings",
        shortTitle: "Equity Changes",
        category: "Financial Accounting",
        summary: "Study retained earnings, dividends, prior-period adjustments, and statement-of-changes-in-equity logic before relying on the rollforward calculator.",
        intro: "Equity questions are easier when students stop treating retained earnings as just a plug figure and instead read how income, distributions, and corrections change the balance.",
        focus: "retained-earnings rollforward and equity-change interpretation",
        workedScenario: "A problem gives beginning retained earnings, current net income, dividends, and an error correction that must be reflected in ending equity.",
        workedResult: "The best answer shows the rollforward cleanly and explains why some changes go through profit while others go directly to equity.",
        checkpointScenario: "A student subtracts dividends from net income first and forgets to reconcile the actual beginning and ending retained earnings balances.",
        checkpointResult: "Equity answers improve when the rollforward is read as a movement schedule, not just one formula line.",
        keywords: ["retained earnings", "dividends", "equity", "statement of changes in equity"],
        scanSignals: ["retained earnings", "dividends declared", "prior period adjustment", "equity"],
        relatedCalculatorPaths: ["/far/retained-earnings-rollforward", "/accounting/earnings-per-share"],
        relatedTopicIds: ["far-framework-accounting-cycle-and-profession"],
    }),
    makeTopic({
        id: "capital-budgeting-arr-eaa-and-ranking",
        title: "Capital Budgeting: ARR, EAA, and Project Ranking",
        shortTitle: "Capital Budgeting Depth",
        category: "Business Math / Finance",
        summary: "Study how ARR and EAA fit beside NPV, IRR, PI, and payback when classwork asks for ranking or interpretation across different project lives.",
        intro: "Students often memorize separate capital-budgeting formulas without understanding why ARR, NPV, and EAA can point to different recommendations.",
        focus: "ranking logic, unequal project lives, and accounting-versus-cash-flow measures",
        workedScenario: "Two projects have different useful lives and the instructor asks for both a discounted recommendation and an annualized comparison.",
        workedResult: "The strongest answer explains when EAA helps, why ARR is accounting-based, and which measure should control the decision.",
        checkpointScenario: "A student compares NPVs directly across unequal project lives without checking whether an annualized comparison is more appropriate.",
        checkpointResult: "Capital-budgeting interpretation gets stronger when the student can explain why the chosen ranking method fits the case.",
        keywords: ["capital budgeting", "arr", "eaa", "project ranking", "unequal lives"],
        scanSignals: ["arr", "equivalent annual annuity", "unequal project lives", "project ranking"],
        relatedCalculatorPaths: ["/finance/accounting-rate-of-return", "/finance/equivalent-annual-annuity", "/finance/capital-budgeting-comparison"],
        relatedTopicIds: ["strategic-business-analysis-and-cost-management"],
    }),
    makeTopic({
        id: "forecasting-afn-and-growth-financing",
        title: "Forecasting Growth: AFN, Retention, and Short-Term Financing Pressure",
        shortTitle: "AFN Forecasting",
        category: "Managerial & Cost Accounting",
        summary: "Study additional funds needed, spontaneous liability support, retained earnings support, and forecast-driven financing pressure.",
        intro: "AFN questions become easier when students separate asset support, spontaneous liabilities, and internally generated financing before solving for the outside gap.",
        focus: "sales growth support and financing-gap interpretation",
        workedScenario: "A sales forecast rises sharply and the student must explain how much support comes from working liabilities and retained earnings before asking for outside financing.",
        workedResult: "The strongest answer explains not only the AFN amount, but also which part of the growth plan is creating the financing pressure.",
        checkpointScenario: "A student treats every increase in sales as if it requires equal outside financing even when retention and spontaneous liabilities already cover part of the need.",
        checkpointResult: "Forecasting answers improve when the financing gap is decomposed rather than treated as one blind percentage.",
        keywords: ["afn", "additional funds needed", "forecasting", "retention ratio"],
        scanSignals: ["additional funds needed", "afn", "retention ratio", "projected sales"],
        relatedCalculatorPaths: ["/business/additional-funds-needed", "/accounting/working-capital-planner"],
        relatedTopicIds: ["strategic-business-analysis-and-cost-management"],
    }),
    makeTopic({
        id: "tax-business-regimes-and-percentage-tax",
        title: "Tax: Business Tax Regimes, VAT vs Percentage Tax, and Compliance Framing",
        shortTitle: "Business Tax Regimes",
        category: "Taxation",
        summary: "Review when business-tax cases belong to VAT, percentage tax, or broader compliance analysis before computing the amount due.",
        intro: "Business-tax errors often come from choosing the wrong regime first. Students need to classify the tax base and applicable system before pressing any calculator.",
        focus: "business-tax classification, tax base, and compliance framing",
        workedScenario: "A business-tax case gives gross sales and asks whether the answer belongs under percentage tax or a different tax regime.",
        workedResult: "The best answer identifies the tax regime first, then computes the due amount only after the correct base and rate are confirmed.",
        checkpointScenario: "A student computes percentage tax immediately without checking whether the facts actually describe a VAT case.",
        checkpointResult: "Tax answers become more accurate when regime classification happens before arithmetic.",
        keywords: ["percentage tax", "vat", "business taxation", "tax regime"],
        scanSignals: ["percentage tax", "gross receipts", "vat", "business tax"],
        relatedCalculatorPaths: ["/tax/percentage-tax", "/tax/tax-compliance-review", "/accounting/philippine-vat"],
        relatedTopicIds: ["tax-book-tax-vat-and-compliance"],
    }),
    makeTopic({
        id: "managerial-budget-flow-production-inventory-and-operating-expense",
        title: "Managerial Budget Flow: Production, Inventory, Materials, and Operating Expenses",
        shortTitle: "Budget Flow",
        category: "Managerial & Cost Accounting",
        summary: "Review how the sales budget flows into production, inventory, materials, operating-expense, and cash-planning support instead of memorizing each schedule in isolation.",
        intro: "Budget questions get easier when the schedules are treated as a chain. Sales drives production, production drives materials, inventory policy changes purchases, and the expense schedule must still be split into total versus cash impact.",
        focus: "budget-sequence logic and the difference between accounting totals and cash effects",
        workedScenario: "A problem gives sales expectations, finished-goods policy, beginning inventory, variable selling-expense rate, and non-cash depreciation, then asks which schedules come next and what the cash effect will be.",
        workedResult: "The strongest answer explains the sequence first, then computes only the schedule that fits the next budget step instead of mixing all formulas together.",
        checkpointScenario: "A student moves directly from sales to cash budget without preparing the inventory, materials, or operating-expense support schedules needed by the case.",
        checkpointResult: "Budget answers become more reliable when schedule order is respected and cash-only effects are separated from total expense.",
        keywords: ["budget flow", "production budget", "inventory budget", "operating expense budget", "cash budget"],
        scanSignals: ["production budget", "inventory budget", "operating expenses", "cash budget", "merchandise purchases"],
        relatedCalculatorPaths: [
            "/business/sales-budget",
            "/business/production-budget",
            "/business/direct-materials-purchases-budget",
            "/business/inventory-budget",
            "/business/operating-expense-budget",
            "/business/cash-budget",
        ],
        relatedTopicIds: ["forecasting-afn-and-growth-financing", "operations-forecasting-inventory-and-quality"],
    }),
    makeTopic({
        id: "tax-vat-output-input-and-remittance-logic",
        title: "Tax: VAT Output, Input, and Period Reconciliation",
        shortTitle: "VAT Reconciliation",
        category: "Taxation",
        summary: "Review output VAT, input VAT, VATable classification, and the net-remittance position without treating VAT as a one-step multiplication only.",
        intro: "VAT questions often become unreliable when classification is skipped, so this reviewer path keeps legal treatment, tax base, and period matching visible before computation.",
        focus: "output VAT, input VAT, classification, and the net-remittance position",
        workedScenario: "A case gives taxable sales, VATable purchases, and asks whether the period shows VAT payable or excess input VAT.",
        workedResult: "The strongest answer computes output and input VAT separately, then explains whether the resulting position is payable, balanced, or excess-input in nature.",
        checkpointScenario: "A student multiplies everything by the VAT rate without first deciding whether all amounts are actually VATable.",
        checkpointResult: "A correct VAT answer still depends on classification and period matching, not arithmetic alone.",
        keywords: ["vat", "output vat", "input vat", "vat payable", "vat reconciliation"],
        scanSignals: ["output vat", "input vat", "vat payable", "vatable sales", "vatable purchases"],
        relatedCalculatorPaths: ["/tax/vat-reconciliation", "/tax/percentage-tax", "/tax/tax-compliance-review"],
        relatedTopicIds: ["tax-book-tax-vat-and-compliance", "tax-withholding-transfer-and-incentive-regimes"],
    }),
    makeTopic({
        id: "afar-intercompany-inventory-and-profit-elimination",
        title: "AFAR: Intercompany Inventory and Unrealized Profit Elimination",
        shortTitle: "Intercompany Inventory",
        category: "AFAR / Consolidation",
        summary: "Review markup basis, unsold inventory, and consolidation elimination logic for intercompany inventory-profit cases.",
        intro: "These AFAR problems become much safer when students separate transfer profit, markup basis, and the still-unsold portion before attempting elimination entries.",
        focus: "markup basis, unrealized profit, and consolidation elimination support",
        workedScenario: "A parent transfers goods to a subsidiary at a markup, some inventory remains unsold at year-end, and the case asks for the unrealized profit requiring elimination.",
        workedResult: "The strongest answer isolates the internal profit first, then limits the elimination to the portion still embedded in ending inventory from the group perspective.",
        checkpointScenario: "A student eliminates the full transfer profit even though only part of the inventory remains unsold to outsiders.",
        checkpointResult: "AFAR elimination is stronger when the unrealized portion is identified precisely instead of assuming all transfer profit stays unrealized.",
        keywords: ["intercompany inventory", "unrealized profit", "consolidation elimination", "markup on cost"],
        scanSignals: ["intercompany transfer", "unsold inventory", "markup on cost", "unrealized profit"],
        relatedCalculatorPaths: ["/afar/intercompany-inventory-profit", "/afar/business-combination-analysis"],
        relatedTopicIds: ["afar-business-combinations-and-consolidation", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "far-equity-rollforward-and-statement-of-changes-in-equity",
        title: "FAR: Equity Rollforward and Statement of Changes in Equity",
        shortTitle: "Equity Rollforward",
        category: "Financial Accounting",
        summary: "Study share capital, APIC, retained earnings, OCI, treasury shares, and the statement-of-changes-in-equity format as one coherent FAR reporting topic.",
        intro: "Equity questions become more reliable when each component is rolled forward separately instead of collapsing everything into one retained-earnings shortcut.",
        focus: "equity components, rollforward logic, and statement preparation",
        workedScenario: "A reporting case gives beginning equity balances, current income, OCI, dividends, share issuances, and treasury-share activity, then asks for ending equity presentation.",
        workedResult: "The strongest answer preserves each component's movement and shows how total equity changes without losing the role of treasury shares as a deduction.",
        checkpointScenario: "A student adds treasury shares to equity instead of treating them as a contra-equity balance.",
        checkpointResult: "Statement reliability improves when students distinguish positive equity components from deduction balances and disclose each movement clearly.",
        keywords: ["statement of changes in equity", "retained earnings", "apic", "treasury shares", "oci"],
        scanSignals: ["statement of changes in equity", "share capital", "retained earnings", "treasury shares", "oci"],
        relatedCalculatorPaths: [
            "/far/statement-of-changes-in-equity-builder",
            "/far/retained-earnings-rollforward",
            "/far/cash-flow-statement-builder",
        ],
        relatedTopicIds: ["far-financial-statements-and-disclosure", "integrative-review-and-case-mapping"],
    }),
    makeTopic({
        id: "far-cash-control-petty-cash-and-adjustments",
        title: "FAR: Cash Control, Petty Cash, and Adjusting-Entry Discipline",
        shortTitle: "Cash Control and Adjustments",
        category: "Financial Accounting",
        summary: "Study petty cash, bank reconciliation, and common adjusting-entry logic as one control-and-period-end reviewer path.",
        intro: "Students often know the journal entry but miss the control purpose. Cash control and period-end adjustments are stronger when you ask what was counted, what remains, what was earned or incurred, and what still belongs to the next period.",
        focus: "cash accountability, accrual-versus-deferral logic, and period-end reliability",
        workedScenario: "A case mixes a petty cash count, a prepaid balance, and an accrued salary item while asking which period-end adjustments are still needed.",
        workedResult: "The best answer separates the control issue from the timing issue, then matches each amount to the proper reconciliation or adjusting-entry tool.",
        checkpointScenario: "A student treats every uncovered difference as if it were the same type of adjusting entry.",
        checkpointResult: "Reliable FAR answers classify the difference first: reconciliation shortage or overage, deferral adjustment, or accrual adjustment.",
        keywords: ["petty cash", "bank reconciliation", "adjusting entries", "accrual", "deferral"],
        scanSignals: ["petty cash", "replenishment", "prepaid", "unearned", "accrued expense"],
        relatedCalculatorPaths: [
            "/accounting/petty-cash-reconciliation",
            "/accounting/bank-reconciliation",
            "/accounting/prepaid-expense-adjustment",
            "/accounting/unearned-revenue-adjustment",
            "/accounting/accrued-revenue-adjustment",
            "/accounting/accrued-expense-adjustment",
        ],
        relatedTopicIds: ["far-framework-accounting-cycle-and-profession"],
    }),
    makeTopic({
        id: "managerial-master-budget-completion",
        title: "Managerial: Master Budget Completion from Labor to Income Statement",
        shortTitle: "Master Budget Completion",
        category: "Managerial & Cost Accounting",
        summary: "Connect direct labor, factory overhead, and the budgeted income statement so the master-budget flow feels continuous instead of fragmented.",
        intro: "Students often learn the master budget as separate schedules. This topic shows how the later schedules connect and why the statement-level result depends on them.",
        focus: "direct labor, overhead, and budgeted income-statement completion",
        workedScenario: "A company already prepared sales, production, and direct-materials schedules and now needs labor, overhead, and a budgeted income statement.",
        workedResult: "The best answer shows how later schedules reuse earlier volume assumptions before ending in a statement-level projected profit.",
        checkpointScenario: "A student computes labor and overhead correctly but treats the budgeted income statement as a disconnected final page.",
        checkpointResult: "The budget is stronger when every later schedule is traced back to the production and sales assumptions that created it.",
        keywords: ["master budget", "direct labor budget", "factory overhead budget", "budgeted income statement"],
        scanSignals: ["direct labor hours per unit", "manufacturing overhead budget", "pro forma income statement"],
        relatedCalculatorPaths: ["/business/direct-labor-budget", "/business/factory-overhead-budget", "/business/budgeted-income-statement"],
        relatedTopicIds: ["managerial-budget-flow-production-inventory-materials-and-operating-expenses"],
    }),
    makeTopic({
        id: "far-notes-receivable-and-discounting",
        title: "FAR: Notes Receivable, Maturity Value, and Discounting",
        shortTitle: "Notes and Discounting",
        category: "Financial Accounting",
        summary: "Review note interest, maturity value, and bank discounting as one receivables-and-cash topic.",
        intro: "Discounting cases are easier when note interest and bank discount are treated as different steps instead of one compressed formula.",
        focus: "note interest, maturity value, and proceeds from discounting",
        workedScenario: "A company holds a note receivable, discounts it at a bank before maturity, and needs the maturity value and cash proceeds.",
        workedResult: "The clean answer separates note interest from bank discount and explains why proceeds are lower than maturity value.",
        checkpointScenario: "A student applies the bank discount directly to face value and skips the maturity-value step.",
        checkpointResult: "Strong notes-receivable answers keep the note's own interest separate from the bank's discount charge.",
        keywords: ["notes receivable", "discounted note", "bank discount", "maturity value"],
        scanSignals: ["promissory note", "bank discount", "proceeds from discounting"],
        relatedCalculatorPaths: ["/accounting/notes-interest", "/accounting/notes-receivable-discounting"],
        relatedTopicIds: ["far-framework-accounting-cycle-and-profession", "far-cash-control-petty-cash-and-adjustments"],
    }),
    makeTopic({
        id: "afar-equity-method-and-associate-investments",
        title: "AFAR: Equity Method and Associate Investment Rollforwards",
        shortTitle: "Equity Method",
        category: "AFAR / Consolidation",
        summary: "Understand why share in income increases the investment and dividends reduce it under the equity method.",
        intro: "Associate-investment cases become more manageable when the carrying-amount rollforward is seen as the core logic before later AFAR complications are added.",
        focus: "equity-method investment rollforward and associate accounting",
        workedScenario: "An investor owns significant influence in an investee and must compute its share in income, dividends, and ending investment balance.",
        workedResult: "The best answer treats the investment account as a rollforward rather than a simple dividend-income question.",
        checkpointScenario: "A student records dividends as revenue and leaves the investment carrying amount unchanged.",
        checkpointResult: "The equity method is clearer when dividends are treated as a reduction of the investment balance rather than a fresh revenue line.",
        keywords: ["equity method", "associate", "share in income", "dividends"],
        scanSignals: ["investment in associate", "share in income", "significant influence"],
        relatedCalculatorPaths: ["/afar/equity-method-investment", "/afar/business-combination-analysis"],
        relatedTopicIds: ["afar-business-combinations-and-consolidation"],
    }),
    makeTopic({
        id: "afar-intercompany-ppe-transfer-eliminations",
        title: "AFAR: Intercompany PPE Transfers and Excess Depreciation",
        shortTitle: "PPE Transfer Elimination",
        category: "AFAR / Consolidation",
        summary: "Review unrealized gain reversal and excess-depreciation adjustments on transferred PPE.",
        intro: "Inventory elimination is not the only intercompany-profit topic. PPE transfers add a multi-period depreciation effect that students need to track carefully.",
        focus: "intercompany PPE transfer gain elimination and excess depreciation",
        workedScenario: "A parent transfers equipment to a subsidiary above carrying amount and the case asks for the remaining unrealized gain after one year.",
        workedResult: "A strong answer reverses the unrealized gain and then measures how much of that gain has been realized through excess depreciation.",
        checkpointScenario: "A student eliminates the full transfer gain every year and never updates the remaining balance.",
        checkpointResult: "Later-period AFAR answers are stronger when excess depreciation is recognized as the mechanism that gradually releases intercompany profit.",
        keywords: ["intercompany ppe", "excess depreciation", "equipment transfer", "unamortized gain"],
        scanSignals: ["excess depreciation", "remaining useful life", "intercompany equipment transfer"],
        relatedCalculatorPaths: ["/afar/intercompany-ppe-transfer", "/afar/intercompany-inventory-profit"],
        relatedTopicIds: ["afar-intercompany-inventory-and-profit-elimination", "afar-business-combinations-and-consolidation"],
    }),
];
